//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.RadGrid {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Main {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Main() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.RadGrid.Main", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AddNewRecordImageUrl {
            get {
                return ResourceManager.GetString("AddNewRecordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Add new record 的本地化字符串。
        /// </summary>
        internal static string AddNewRecordText {
            get {
                return ResourceManager.GetString("AddNewRecordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Between 的本地化字符串。
        /// </summary>
        internal static string BetweenText {
            get {
                return ResourceManager.GetString("BetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        internal static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Caption {
            get {
                return ResourceManager.GetString("Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page size: 的本地化字符串。
        /// </summary>
        internal static string ChangePageSizeLabelText {
            get {
                return ResourceManager.GetString("ChangePageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change 的本地化字符串。
        /// </summary>
        internal static string ChangePageSizeLinkButtonText {
            get {
                return ResourceManager.GetString("ChangePageSizeLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse group 的本地化字符串。
        /// </summary>
        internal static string CollapseTooltip {
            get {
                return ResourceManager.GetString("CollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Width: &lt;strong&gt;{0}&lt;/strong&gt; &lt;em&gt;pixels&lt;/em&gt; 的本地化字符串。
        /// </summary>
        internal static string ColumnResizeTooltipFormatString {
            get {
                return ResourceManager.GetString("ColumnResizeTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contains 的本地化字符串。
        /// </summary>
        internal static string ContainsText {
            get {
                return ResourceManager.GetString("ContainsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string CustomText {
            get {
                return ResourceManager.GetString("CustomText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        internal static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DoesNotContain 的本地化字符串。
        /// </summary>
        internal static string DoesNotContainText {
            get {
                return ResourceManager.GetString("DoesNotContainText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to group or reorder 的本地化字符串。
        /// </summary>
        internal static string DragToGroupOrReorder {
            get {
                return ResourceManager.GetString("DragToGroupOrReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag to resize 的本地化字符串。
        /// </summary>
        internal static string DragToResize {
            get {
                return ResourceManager.GetString("DragToResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drop here to reorder 的本地化字符串。
        /// </summary>
        internal static string DropHereToReorder {
            get {
                return ResourceManager.GetString("DropHereToReorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EndsWith 的本地化字符串。
        /// </summary>
        internal static string EndsWithText {
            get {
                return ResourceManager.GetString("EndsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EqualTo 的本地化字符串。
        /// </summary>
        internal static string EqualToText {
            get {
                return ResourceManager.GetString("EqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand group 的本地化字符串。
        /// </summary>
        internal static string ExpandTooltip {
            get {
                return ResourceManager.GetString("ExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ExportToCsvImageUrl {
            get {
                return ResourceManager.GetString("ExportToCsvImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to CSV 的本地化字符串。
        /// </summary>
        internal static string ExportToCsvText {
            get {
                return ResourceManager.GetString("ExportToCsvText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ExportToExcelImageUrl {
            get {
                return ResourceManager.GetString("ExportToExcelImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Excel 的本地化字符串。
        /// </summary>
        internal static string ExportToExcelText {
            get {
                return ResourceManager.GetString("ExportToExcelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ExportToPdfImageUrl {
            get {
                return ResourceManager.GetString("ExportToPdfImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to PDF 的本地化字符串。
        /// </summary>
        internal static string ExportToPdfText {
            get {
                return ResourceManager.GetString("ExportToPdfText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string ExportToWordImageUrl {
            get {
                return ResourceManager.GetString("ExportToWordImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export to Word 的本地化字符串。
        /// </summary>
        internal static string ExportToWordText {
            get {
                return ResourceManager.GetString("ExportToWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FilterExpression {
            get {
                return ResourceManager.GetString("FilterExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string FilterImageToolTip {
            get {
                return ResourceManager.GetString("FilterImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First Page 的本地化字符串。
        /// </summary>
        internal static string FirstPageToolTip {
            get {
                return ResourceManager.GetString("FirstPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page: 的本地化字符串。
        /// </summary>
        internal static string GoToPageLabelText {
            get {
                return ResourceManager.GetString("GoToPageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go 的本地化字符串。
        /// </summary>
        internal static string GoToPageLinkButtonText {
            get {
                return ResourceManager.GetString("GoToPageLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterThanOrEqualTo 的本地化字符串。
        /// </summary>
        internal static string GreaterThanOrEqualToText {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GreaterThan 的本地化字符串。
        /// </summary>
        internal static string GreaterThanText {
            get {
                return ResourceManager.GetString("GreaterThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ;  的本地化字符串。
        /// </summary>
        internal static string GroupByFieldsSeparator {
            get {
                return ResourceManager.GetString("GroupByFieldsSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ... group continued from the previous page.  的本地化字符串。
        /// </summary>
        internal static string GroupContinuedFormatString {
            get {
                return ResourceManager.GetString("GroupContinuedFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Group continues on the next page. 的本地化字符串。
        /// </summary>
        internal static string GroupContinuesFormatString {
            get {
                return ResourceManager.GetString("GroupContinuesFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag a column header and drop it here to group by that column 的本地化字符串。
        /// </summary>
        internal static string GroupPanelText {
            get {
                return ResourceManager.GetString("GroupPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing {0} of {1} items. 的本地化字符串。
        /// </summary>
        internal static string GroupSplitDisplayFormat {
            get {
                return ResourceManager.GetString("GroupSplitDisplayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  ({0}) 的本地化字符串。
        /// </summary>
        internal static string GroupSplitFormat {
            get {
                return ResourceManager.GetString("GroupSplitFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Aggregates 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuAggregates {
            get {
                return ResourceManager.GetString("HeaderContextMenuAggregates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 And 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuAndLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuAndLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avg 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuAvgAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuAvgAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Best Fit 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuBestFitText {
            get {
                return ResourceManager.GetString("HeaderContextMenuBestFitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Filter 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuClearButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuClearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Columns 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuColumns {
            get {
                return ResourceManager.GetString("HeaderContextMenuColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Count 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuCountAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CountDistinct 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuCountDistinctAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCountDistinctAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuCustomAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuCustomAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuFilterButton {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Filter 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuFilterItemText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFilterItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 First 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuFirstAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuFirstAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group By 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuLastAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuLastAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Max 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuMaxAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMaxAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Min 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuMinAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuMinAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 None 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuNoneAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuNoneAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show rows with value that 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuRowsLabel {
            get {
                return ResourceManager.GetString("HeaderContextMenuRowsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Ascending 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuSortAsc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear Sorting 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuSortClear {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Descending 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuSortDesc {
            get {
                return ResourceManager.GetString("HeaderContextMenuSortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sum 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuSumAggregateText {
            get {
                return ResourceManager.GetString("HeaderContextMenuSumAggregateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ungroup 的本地化字符串。
        /// </summary>
        internal static string HeaderContextMenuUnGroupBy {
            get {
                return ResourceManager.GetString("HeaderContextMenuUnGroupBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collapse 的本地化字符串。
        /// </summary>
        internal static string HierarchyCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchyCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expand 的本地化字符串。
        /// </summary>
        internal static string HierarchyExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchyExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self reference collapse 的本地化字符串。
        /// </summary>
        internal static string HierarchySelfCollapseTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfCollapseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Self reference expand 的本地化字符串。
        /// </summary>
        internal static string HierarchySelfExpandTooltip {
            get {
                return ResourceManager.GetString("HierarchySelfExpandTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert 的本地化字符串。
        /// </summary>
        internal static string InsertText {
            get {
                return ResourceManager.GetString("InsertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsEmpty 的本地化字符串。
        /// </summary>
        internal static string IsEmptyText {
            get {
                return ResourceManager.GetString("IsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IsNull 的本地化字符串。
        /// </summary>
        internal static string IsNullText {
            get {
                return ResourceManager.GetString("IsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Last Page 的本地化字符串。
        /// </summary>
        internal static string LastPageToolTip {
            get {
                return ResourceManager.GetString("LastPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessThanOrEqualTo 的本地化字符串。
        /// </summary>
        internal static string LessThanOrEqualToText {
            get {
                return ResourceManager.GetString("LessThanOrEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LessThan 的本地化字符串。
        /// </summary>
        internal static string LessThanText {
            get {
                return ResourceManager.GetString("LessThanText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading... 的本地化字符串。
        /// </summary>
        internal static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Pages 的本地化字符串。
        /// </summary>
        internal static string NextPagesToolTip {
            get {
                return ResourceManager.GetString("NextPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Next Page 的本地化字符串。
        /// </summary>
        internal static string NextPageToolTip {
            get {
                return ResourceManager.GetString("NextPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No child records to display. 的本地化字符串。
        /// </summary>
        internal static string NoDetailRecordsText {
            get {
                return ResourceManager.GetString("NoDetailRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoFilter 的本地化字符串。
        /// </summary>
        internal static string NoFilterText {
            get {
                return ResourceManager.GetString("NoFilterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No records to display. 的本地化字符串。
        /// </summary>
        internal static string NoMasterRecordsText {
            get {
                return ResourceManager.GetString("NoMasterRecordsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotBetween 的本地化字符串。
        /// </summary>
        internal static string NotBetweenText {
            get {
                return ResourceManager.GetString("NotBetweenText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotEqualTo 的本地化字符串。
        /// </summary>
        internal static string NotEqualToText {
            get {
                return ResourceManager.GetString("NotEqualToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotIsEmpty 的本地化字符串。
        /// </summary>
        internal static string NotIsEmptyText {
            get {
                return ResourceManager.GetString("NotIsEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NotIsNull 的本地化字符串。
        /// </summary>
        internal static string NotIsNullText {
            get {
                return ResourceManager.GetString("NotIsNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 of {0} 的本地化字符串。
        /// </summary>
        internal static string PageOfLabelText {
            get {
                return ResourceManager.GetString("PageOfLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Change page: {4} &amp;nbsp;Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt;, items &lt;strong&gt;{2}&lt;/strong&gt; to &lt;strong&gt;{3}&lt;/strong&gt; of &lt;strong&gt;{5}&lt;/strong&gt;. 的本地化字符串。
        /// </summary>
        internal static string PagerTextFormat {
            get {
                return ResourceManager.GetString("PagerTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page &lt;strong&gt;{0}&lt;/strong&gt; of &lt;strong&gt;{1}&lt;/strong&gt; 的本地化字符串。
        /// </summary>
        internal static string PagerTooltipFormatString {
            get {
                return ResourceManager.GetString("PagerTooltipFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Page size: 的本地化字符串。
        /// </summary>
        internal static string PageSizeLabelText {
            get {
                return ResourceManager.GetString("PageSizeLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Pages 的本地化字符串。
        /// </summary>
        internal static string PrevPagesToolTip {
            get {
                return ResourceManager.GetString("PrevPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string PrevPageText {
            get {
                return ResourceManager.GetString("PrevPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Previous Page 的本地化字符串。
        /// </summary>
        internal static string PrevPageToolTip {
            get {
                return ResourceManager.GetString("PrevPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string RefreshImageUrl {
            get {
                return ResourceManager.GetString("RefreshImageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please do not remove this key. 的本地化字符串。
        /// </summary>
        internal static string ReservedResource {
            get {
                return ResourceManager.GetString("ReservedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted asc 的本地化字符串。
        /// </summary>
        internal static string SortedAscToolTip {
            get {
                return ResourceManager.GetString("SortedAscToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorted desc 的本地化字符串。
        /// </summary>
        internal static string SortedDescToolTip {
            get {
                return ResourceManager.GetString("SortedDescToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to sort 的本地化字符串。
        /// </summary>
        internal static string SortToolTip {
            get {
                return ResourceManager.GetString("SortToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StartsWith 的本地化字符串。
        /// </summary>
        internal static string StartsWithText {
            get {
                return ResourceManager.GetString("StartsWithText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ready 的本地化字符串。
        /// </summary>
        internal static string StatusReadyText {
            get {
                return ResourceManager.GetString("StatusReadyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click here to ungroup 的本地化字符串。
        /// </summary>
        internal static string UnGroupButtonTooltip {
            get {
                return ResourceManager.GetString("UnGroupButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Drag out of the bar to ungroup 的本地化字符串。
        /// </summary>
        internal static string UnGroupTooltip {
            get {
                return ResourceManager.GetString("UnGroupTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        internal static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
    }
}
