//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace mms.k2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="K2WebServiceForMMSSoap", Namespace="http://tempuri.org/")]
    public partial class K2WebServiceForMMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback StartNewProcessOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteProcessInstOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApproveHeaderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApproveBodyOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendChuKuNotificationOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public K2WebServiceForMMS() {
            this.Url = global::mms.Properties.Settings.Default.mms_k2_K2WebServiceForMMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event StartNewProcessCompletedEventHandler StartNewProcessCompleted;
        
        /// <remarks/>
        public event DeleteProcessInstCompletedEventHandler DeleteProcessInstCompleted;
        
        /// <remarks/>
        public event GetApproveHeaderCompletedEventHandler GetApproveHeaderCompleted;
        
        /// <remarks/>
        public event GetApproveBodyCompletedEventHandler GetApproveBodyCompleted;
        
        /// <remarks/>
        public event SendChuKuNotificationCompletedEventHandler SendChuKuNotificationCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StartNewProcess", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool StartNewProcess(SubmitInfoModel SubmitInfo) {
            object[] results = this.Invoke("StartNewProcess", new object[] {
                        SubmitInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void StartNewProcessAsync(SubmitInfoModel SubmitInfo) {
            this.StartNewProcessAsync(SubmitInfo, null);
        }
        
        /// <remarks/>
        public void StartNewProcessAsync(SubmitInfoModel SubmitInfo, object userState) {
            if ((this.StartNewProcessOperationCompleted == null)) {
                this.StartNewProcessOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStartNewProcessOperationCompleted);
            }
            this.InvokeAsync("StartNewProcess", new object[] {
                        SubmitInfo}, this.StartNewProcessOperationCompleted, userState);
        }
        
        private void OnStartNewProcessOperationCompleted(object arg) {
            if ((this.StartNewProcessCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StartNewProcessCompleted(this, new StartNewProcessCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteProcessInst", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteProcessInst(SubmitInfoModel SubmitInfo, bool OnlyProcess) {
            object[] results = this.Invoke("DeleteProcessInst", new object[] {
                        SubmitInfo,
                        OnlyProcess});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteProcessInstAsync(SubmitInfoModel SubmitInfo, bool OnlyProcess) {
            this.DeleteProcessInstAsync(SubmitInfo, OnlyProcess, null);
        }
        
        /// <remarks/>
        public void DeleteProcessInstAsync(SubmitInfoModel SubmitInfo, bool OnlyProcess, object userState) {
            if ((this.DeleteProcessInstOperationCompleted == null)) {
                this.DeleteProcessInstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteProcessInstOperationCompleted);
            }
            this.InvokeAsync("DeleteProcessInst", new object[] {
                        SubmitInfo,
                        OnlyProcess}, this.DeleteProcessInstOperationCompleted, userState);
        }
        
        private void OnDeleteProcessInstOperationCompleted(object arg) {
            if ((this.DeleteProcessInstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteProcessInstCompleted(this, new DeleteProcessInstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApproveHeader", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApproveInfoHead GetApproveHeader(SubmitInfoModel SubmitInfo) {
            object[] results = this.Invoke("GetApproveHeader", new object[] {
                        SubmitInfo});
            return ((ApproveInfoHead)(results[0]));
        }
        
        /// <remarks/>
        public void GetApproveHeaderAsync(SubmitInfoModel SubmitInfo) {
            this.GetApproveHeaderAsync(SubmitInfo, null);
        }
        
        /// <remarks/>
        public void GetApproveHeaderAsync(SubmitInfoModel SubmitInfo, object userState) {
            if ((this.GetApproveHeaderOperationCompleted == null)) {
                this.GetApproveHeaderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApproveHeaderOperationCompleted);
            }
            this.InvokeAsync("GetApproveHeader", new object[] {
                        SubmitInfo}, this.GetApproveHeaderOperationCompleted, userState);
        }
        
        private void OnGetApproveHeaderOperationCompleted(object arg) {
            if ((this.GetApproveHeaderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApproveHeaderCompleted(this, new GetApproveHeaderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetApproveBody", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ApproveInfoBody[] GetApproveBody(SubmitInfoModel SubmitInfo) {
            object[] results = this.Invoke("GetApproveBody", new object[] {
                        SubmitInfo});
            return ((ApproveInfoBody[])(results[0]));
        }
        
        /// <remarks/>
        public void GetApproveBodyAsync(SubmitInfoModel SubmitInfo) {
            this.GetApproveBodyAsync(SubmitInfo, null);
        }
        
        /// <remarks/>
        public void GetApproveBodyAsync(SubmitInfoModel SubmitInfo, object userState) {
            if ((this.GetApproveBodyOperationCompleted == null)) {
                this.GetApproveBodyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApproveBodyOperationCompleted);
            }
            this.InvokeAsync("GetApproveBody", new object[] {
                        SubmitInfo}, this.GetApproveBodyOperationCompleted, userState);
        }
        
        private void OnGetApproveBodyOperationCompleted(object arg) {
            if ((this.GetApproveBodyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApproveBodyCompleted(this, new GetApproveBodyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendChuKuNotification", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendChuKuNotification(SendChuKuNotificationModel ChuKuInfo) {
            object[] results = this.Invoke("SendChuKuNotification", new object[] {
                        ChuKuInfo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SendChuKuNotificationAsync(SendChuKuNotificationModel ChuKuInfo) {
            this.SendChuKuNotificationAsync(ChuKuInfo, null);
        }
        
        /// <remarks/>
        public void SendChuKuNotificationAsync(SendChuKuNotificationModel ChuKuInfo, object userState) {
            if ((this.SendChuKuNotificationOperationCompleted == null)) {
                this.SendChuKuNotificationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendChuKuNotificationOperationCompleted);
            }
            this.InvokeAsync("SendChuKuNotification", new object[] {
                        ChuKuInfo}, this.SendChuKuNotificationOperationCompleted, userState);
        }
        
        private void OnSendChuKuNotificationOperationCompleted(object arg) {
            if ((this.SendChuKuNotificationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendChuKuNotificationCompleted(this, new SendChuKuNotificationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SubmitInfoModel {
        
        private string userAccountField;
        
        private string diaoDuApproveAccountField;
        
        private string xingHaoJiHuaYuanApproveField;
        
        private string wuZiJiHuaYuanApproveField;
        
        private int processInstIDField;
        
        private int mMS_IDField;
        
        private int typeField;
        
        private string itemCodeField;
        
        private int material_IdField;
        
        private string applicantField;
        
        private string deptField;
        
        private System.DateTime applicationTimeField;
        
        private string contactInformationField;
        
        private string theMaterialWayField;
        
        private string taskCodeField;
        
        private string drawing_NoField;
        
        private string draft_CodeField;
        
        private int quantityField;
        
        private System.Nullable<System.DateTime> feedingTimeField;
        
        private bool isDispatchField;
        
        private bool isConfirmField;
        
        private string remarkField;
        
        private string materialTypeField;
        
        private string material_NameField;
        
        private string material_MarkField;
        
        private string cN_Material_StateField;
        
        private string material_Tech_ConditionField;
        
        private string rough_SpecField;
        
        private string mat_Rough_WeightField;
        
        private string mat_UnitField;
        
        private string rough_SizeField;
        
        private string pleaseTakeQualityField;
        
        private string rqHeaderIdField;
        
        private string rqLineIdField;
        
        private string rqDeptField;
        
        private int appStateField;
        
        private string returnReasonField;
        
        private bool is_DelField;
        
        private string tuiKuContextField;
        
        /// <remarks/>
        public string UserAccount {
            get {
                return this.userAccountField;
            }
            set {
                this.userAccountField = value;
            }
        }
        
        /// <remarks/>
        public string DiaoDuApproveAccount {
            get {
                return this.diaoDuApproveAccountField;
            }
            set {
                this.diaoDuApproveAccountField = value;
            }
        }
        
        /// <remarks/>
        public string XingHaoJiHuaYuanApprove {
            get {
                return this.xingHaoJiHuaYuanApproveField;
            }
            set {
                this.xingHaoJiHuaYuanApproveField = value;
            }
        }
        
        /// <remarks/>
        public string WuZiJiHuaYuanApprove {
            get {
                return this.wuZiJiHuaYuanApproveField;
            }
            set {
                this.wuZiJiHuaYuanApproveField = value;
            }
        }
        
        /// <remarks/>
        public int ProcessInstID {
            get {
                return this.processInstIDField;
            }
            set {
                this.processInstIDField = value;
            }
        }
        
        /// <remarks/>
        public int MMS_ID {
            get {
                return this.mMS_IDField;
            }
            set {
                this.mMS_IDField = value;
            }
        }
        
        /// <remarks/>
        public int Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public int Material_Id {
            get {
                return this.material_IdField;
            }
            set {
                this.material_IdField = value;
            }
        }
        
        /// <remarks/>
        public string Applicant {
            get {
                return this.applicantField;
            }
            set {
                this.applicantField = value;
            }
        }
        
        /// <remarks/>
        public string Dept {
            get {
                return this.deptField;
            }
            set {
                this.deptField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ApplicationTime {
            get {
                return this.applicationTimeField;
            }
            set {
                this.applicationTimeField = value;
            }
        }
        
        /// <remarks/>
        public string ContactInformation {
            get {
                return this.contactInformationField;
            }
            set {
                this.contactInformationField = value;
            }
        }
        
        /// <remarks/>
        public string TheMaterialWay {
            get {
                return this.theMaterialWayField;
            }
            set {
                this.theMaterialWayField = value;
            }
        }
        
        /// <remarks/>
        public string TaskCode {
            get {
                return this.taskCodeField;
            }
            set {
                this.taskCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Drawing_No {
            get {
                return this.drawing_NoField;
            }
            set {
                this.drawing_NoField = value;
            }
        }
        
        /// <remarks/>
        public string Draft_Code {
            get {
                return this.draft_CodeField;
            }
            set {
                this.draft_CodeField = value;
            }
        }
        
        /// <remarks/>
        public int Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> FeedingTime {
            get {
                return this.feedingTimeField;
            }
            set {
                this.feedingTimeField = value;
            }
        }
        
        /// <remarks/>
        public bool IsDispatch {
            get {
                return this.isDispatchField;
            }
            set {
                this.isDispatchField = value;
            }
        }
        
        /// <remarks/>
        public bool IsConfirm {
            get {
                return this.isConfirmField;
            }
            set {
                this.isConfirmField = value;
            }
        }
        
        /// <remarks/>
        public string Remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
            }
        }
        
        /// <remarks/>
        public string MaterialType {
            get {
                return this.materialTypeField;
            }
            set {
                this.materialTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Material_Name {
            get {
                return this.material_NameField;
            }
            set {
                this.material_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Material_Mark {
            get {
                return this.material_MarkField;
            }
            set {
                this.material_MarkField = value;
            }
        }
        
        /// <remarks/>
        public string CN_Material_State {
            get {
                return this.cN_Material_StateField;
            }
            set {
                this.cN_Material_StateField = value;
            }
        }
        
        /// <remarks/>
        public string Material_Tech_Condition {
            get {
                return this.material_Tech_ConditionField;
            }
            set {
                this.material_Tech_ConditionField = value;
            }
        }
        
        /// <remarks/>
        public string Rough_Spec {
            get {
                return this.rough_SpecField;
            }
            set {
                this.rough_SpecField = value;
            }
        }
        
        /// <remarks/>
        public string Mat_Rough_Weight {
            get {
                return this.mat_Rough_WeightField;
            }
            set {
                this.mat_Rough_WeightField = value;
            }
        }
        
        /// <remarks/>
        public string Mat_Unit {
            get {
                return this.mat_UnitField;
            }
            set {
                this.mat_UnitField = value;
            }
        }
        
        /// <remarks/>
        public string Rough_Size {
            get {
                return this.rough_SizeField;
            }
            set {
                this.rough_SizeField = value;
            }
        }
        
        /// <remarks/>
        public string PleaseTakeQuality {
            get {
                return this.pleaseTakeQualityField;
            }
            set {
                this.pleaseTakeQualityField = value;
            }
        }
        
        /// <remarks/>
        public string RqHeaderId {
            get {
                return this.rqHeaderIdField;
            }
            set {
                this.rqHeaderIdField = value;
            }
        }
        
        /// <remarks/>
        public string RqLineId {
            get {
                return this.rqLineIdField;
            }
            set {
                this.rqLineIdField = value;
            }
        }
        
        /// <remarks/>
        public string RqDept {
            get {
                return this.rqDeptField;
            }
            set {
                this.rqDeptField = value;
            }
        }
        
        /// <remarks/>
        public int AppState {
            get {
                return this.appStateField;
            }
            set {
                this.appStateField = value;
            }
        }
        
        /// <remarks/>
        public string ReturnReason {
            get {
                return this.returnReasonField;
            }
            set {
                this.returnReasonField = value;
            }
        }
        
        /// <remarks/>
        public bool Is_Del {
            get {
                return this.is_DelField;
            }
            set {
                this.is_DelField = value;
            }
        }
        
        /// <remarks/>
        public string TuiKuContext {
            get {
                return this.tuiKuContextField;
            }
            set {
                this.tuiKuContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SendChuKuNotificationModel {
        
        private int processInstIDField;
        
        private string rQ_HeadIDField;
        
        private string rQ_BodyIDField;
        
        private System.DateTime sendTimeField;
        
        /// <remarks/>
        public int ProcessInstID {
            get {
                return this.processInstIDField;
            }
            set {
                this.processInstIDField = value;
            }
        }
        
        /// <remarks/>
        public string RQ_HeadID {
            get {
                return this.rQ_HeadIDField;
            }
            set {
                this.rQ_HeadIDField = value;
            }
        }
        
        /// <remarks/>
        public string RQ_BodyID {
            get {
                return this.rQ_BodyIDField;
            }
            set {
                this.rQ_BodyIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SendTime {
            get {
                return this.sendTimeField;
            }
            set {
                this.sendTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveInfoBody {
        
        private string activityNameField;
        
        private string approveLeaderNameField;
        
        private string approveLeaderDeptField;
        
        private string resultField;
        
        private string reasonField;
        
        private System.DateTime approveTimeField;
        
        /// <remarks/>
        public string ActivityName {
            get {
                return this.activityNameField;
            }
            set {
                this.activityNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApproveLeaderName {
            get {
                return this.approveLeaderNameField;
            }
            set {
                this.approveLeaderNameField = value;
            }
        }
        
        /// <remarks/>
        public string ApproveLeaderDept {
            get {
                return this.approveLeaderDeptField;
            }
            set {
                this.approveLeaderDeptField = value;
            }
        }
        
        /// <remarks/>
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public string Reason {
            get {
                return this.reasonField;
            }
            set {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ApproveTime {
            get {
                return this.approveTimeField;
            }
            set {
                this.approveTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveInfoHead {
        
        private int processInstIDField;
        
        private int mMS_IDField;
        
        private int appStateField;
        
        private string approvingActivityField;
        
        private string approvingUserField;
        
        private string approvingUserDeptField;
        
        /// <remarks/>
        public int ProcessInstID {
            get {
                return this.processInstIDField;
            }
            set {
                this.processInstIDField = value;
            }
        }
        
        /// <remarks/>
        public int MMS_ID {
            get {
                return this.mMS_IDField;
            }
            set {
                this.mMS_IDField = value;
            }
        }
        
        /// <remarks/>
        public int AppState {
            get {
                return this.appStateField;
            }
            set {
                this.appStateField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovingActivity {
            get {
                return this.approvingActivityField;
            }
            set {
                this.approvingActivityField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovingUser {
            get {
                return this.approvingUserField;
            }
            set {
                this.approvingUserField = value;
            }
        }
        
        /// <remarks/>
        public string ApprovingUserDept {
            get {
                return this.approvingUserDeptField;
            }
            set {
                this.approvingUserDeptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void StartNewProcessCompletedEventHandler(object sender, StartNewProcessCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StartNewProcessCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal StartNewProcessCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void DeleteProcessInstCompletedEventHandler(object sender, DeleteProcessInstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteProcessInstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteProcessInstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetApproveHeaderCompletedEventHandler(object sender, GetApproveHeaderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApproveHeaderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApproveHeaderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApproveInfoHead Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApproveInfoHead)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void GetApproveBodyCompletedEventHandler(object sender, GetApproveBodyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApproveBodyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApproveBodyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApproveInfoBody[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApproveInfoBody[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SendChuKuNotificationCompletedEventHandler(object sender, SendChuKuNotificationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendChuKuNotificationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendChuKuNotificationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591