//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace mms.SmarTeam {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ItemsSoap", Namespace="http://tempuri.org/")]
    public partial class Items : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetByDrawingNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByDrawingNoAndLastPhaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByDrawingNoAndPhaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByDrawingNo222OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByDrawingNoBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByPartNameBOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetById2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildren2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChildrenByUnitOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUnitChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTypeChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTypeChildrenByDrawingNoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetParentsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDetailsByIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemsTypeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetPhaseNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLingJianTypeNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback HasCaiLDEOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetItemTypeOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Items() {
            this.Url = global::mms.Properties.Settings.Default.mms_SmarTeam_Items;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetByDrawingNoCompletedEventHandler GetByDrawingNoCompleted;
        
        /// <remarks/>
        public event GetByDrawingNoAndLastPhaseCompletedEventHandler GetByDrawingNoAndLastPhaseCompleted;
        
        /// <remarks/>
        public event GetByDrawingNoAndPhaseCompletedEventHandler GetByDrawingNoAndPhaseCompleted;
        
        /// <remarks/>
        public event GetByDrawingNo222CompletedEventHandler GetByDrawingNo222Completed;
        
        /// <remarks/>
        public event GetByDrawingNoBCompletedEventHandler GetByDrawingNoBCompleted;
        
        /// <remarks/>
        public event GetByPartNameBCompletedEventHandler GetByPartNameBCompleted;
        
        /// <remarks/>
        public event GetByIdCompletedEventHandler GetByIdCompleted;
        
        /// <remarks/>
        public event GetById2CompletedEventHandler GetById2Completed;
        
        /// <remarks/>
        public event GetChildrenCompletedEventHandler GetChildrenCompleted;
        
        /// <remarks/>
        public event GetChildren2CompletedEventHandler GetChildren2Completed;
        
        /// <remarks/>
        public event GetChildrenByUnitCompletedEventHandler GetChildrenByUnitCompleted;
        
        /// <remarks/>
        public event GetUnitChildrenCompletedEventHandler GetUnitChildrenCompleted;
        
        /// <remarks/>
        public event GetTypeChildrenCompletedEventHandler GetTypeChildrenCompleted;
        
        /// <remarks/>
        public event GetTypeChildrenByDrawingNoCompletedEventHandler GetTypeChildrenByDrawingNoCompleted;
        
        /// <remarks/>
        public event GetParentsCompletedEventHandler GetParentsCompleted;
        
        /// <remarks/>
        public event GetItemsCountCompletedEventHandler GetItemsCountCompleted;
        
        /// <remarks/>
        public event GetDetailsByIDCompletedEventHandler GetDetailsByIDCompleted;
        
        /// <remarks/>
        public event GetItemsTypeCompletedEventHandler GetItemsTypeCompleted;
        
        /// <remarks/>
        public event GetPhaseNameCompletedEventHandler GetPhaseNameCompleted;
        
        /// <remarks/>
        public event GetLingJianTypeNameCompletedEventHandler GetLingJianTypeNameCompleted;
        
        /// <remarks/>
        public event GetDepNameCompletedEventHandler GetDepNameCompleted;
        
        /// <remarks/>
        public event HasCaiLDECompletedEventHandler HasCaiLDECompleted;
        
        /// <remarks/>
        public event GetItemTypeCompletedEventHandler GetItemTypeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByDrawingNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetByDrawingNo(string DrawingNo) {
            object[] results = this.Invoke("GetByDrawingNo", new object[] {
                        DrawingNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetByDrawingNoAsync(string DrawingNo) {
            this.GetByDrawingNoAsync(DrawingNo, null);
        }
        
        /// <remarks/>
        public void GetByDrawingNoAsync(string DrawingNo, object userState) {
            if ((this.GetByDrawingNoOperationCompleted == null)) {
                this.GetByDrawingNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByDrawingNoOperationCompleted);
            }
            this.InvokeAsync("GetByDrawingNo", new object[] {
                        DrawingNo}, this.GetByDrawingNoOperationCompleted, userState);
        }
        
        private void OnGetByDrawingNoOperationCompleted(object arg) {
            if ((this.GetByDrawingNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByDrawingNoCompleted(this, new GetByDrawingNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByDrawingNoAndLastPhase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetByDrawingNoAndLastPhase(string DrawingNo) {
            object[] results = this.Invoke("GetByDrawingNoAndLastPhase", new object[] {
                        DrawingNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetByDrawingNoAndLastPhaseAsync(string DrawingNo) {
            this.GetByDrawingNoAndLastPhaseAsync(DrawingNo, null);
        }
        
        /// <remarks/>
        public void GetByDrawingNoAndLastPhaseAsync(string DrawingNo, object userState) {
            if ((this.GetByDrawingNoAndLastPhaseOperationCompleted == null)) {
                this.GetByDrawingNoAndLastPhaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByDrawingNoAndLastPhaseOperationCompleted);
            }
            this.InvokeAsync("GetByDrawingNoAndLastPhase", new object[] {
                        DrawingNo}, this.GetByDrawingNoAndLastPhaseOperationCompleted, userState);
        }
        
        private void OnGetByDrawingNoAndLastPhaseOperationCompleted(object arg) {
            if ((this.GetByDrawingNoAndLastPhaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByDrawingNoAndLastPhaseCompleted(this, new GetByDrawingNoAndLastPhaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByDrawingNoAndPhase", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetByDrawingNoAndPhase(string DrawingNo, string Phase, string Site) {
            object[] results = this.Invoke("GetByDrawingNoAndPhase", new object[] {
                        DrawingNo,
                        Phase,
                        Site});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetByDrawingNoAndPhaseAsync(string DrawingNo, string Phase, string Site) {
            this.GetByDrawingNoAndPhaseAsync(DrawingNo, Phase, Site, null);
        }
        
        /// <remarks/>
        public void GetByDrawingNoAndPhaseAsync(string DrawingNo, string Phase, string Site, object userState) {
            if ((this.GetByDrawingNoAndPhaseOperationCompleted == null)) {
                this.GetByDrawingNoAndPhaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByDrawingNoAndPhaseOperationCompleted);
            }
            this.InvokeAsync("GetByDrawingNoAndPhase", new object[] {
                        DrawingNo,
                        Phase,
                        Site}, this.GetByDrawingNoAndPhaseOperationCompleted, userState);
        }
        
        private void OnGetByDrawingNoAndPhaseOperationCompleted(object arg) {
            if ((this.GetByDrawingNoAndPhaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByDrawingNoAndPhaseCompleted(this, new GetByDrawingNoAndPhaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByDrawingNo222", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetByDrawingNo222(string DrawingNo) {
            object[] results = this.Invoke("GetByDrawingNo222", new object[] {
                        DrawingNo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetByDrawingNo222Async(string DrawingNo) {
            this.GetByDrawingNo222Async(DrawingNo, null);
        }
        
        /// <remarks/>
        public void GetByDrawingNo222Async(string DrawingNo, object userState) {
            if ((this.GetByDrawingNo222OperationCompleted == null)) {
                this.GetByDrawingNo222OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByDrawingNo222OperationCompleted);
            }
            this.InvokeAsync("GetByDrawingNo222", new object[] {
                        DrawingNo}, this.GetByDrawingNo222OperationCompleted, userState);
        }
        
        private void OnGetByDrawingNo222OperationCompleted(object arg) {
            if ((this.GetByDrawingNo222Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByDrawingNo222Completed(this, new GetByDrawingNo222CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByDrawingNoB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetByDrawingNoB(string DrawingNo) {
            object[] results = this.Invoke("GetByDrawingNoB", new object[] {
                        DrawingNo});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetByDrawingNoBAsync(string DrawingNo) {
            this.GetByDrawingNoBAsync(DrawingNo, null);
        }
        
        /// <remarks/>
        public void GetByDrawingNoBAsync(string DrawingNo, object userState) {
            if ((this.GetByDrawingNoBOperationCompleted == null)) {
                this.GetByDrawingNoBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByDrawingNoBOperationCompleted);
            }
            this.InvokeAsync("GetByDrawingNoB", new object[] {
                        DrawingNo}, this.GetByDrawingNoBOperationCompleted, userState);
        }
        
        private void OnGetByDrawingNoBOperationCompleted(object arg) {
            if ((this.GetByDrawingNoBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByDrawingNoBCompleted(this, new GetByDrawingNoBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetByPartNameB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetByPartNameB(string PartName) {
            object[] results = this.Invoke("GetByPartNameB", new object[] {
                        PartName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetByPartNameBAsync(string PartName) {
            this.GetByPartNameBAsync(PartName, null);
        }
        
        /// <remarks/>
        public void GetByPartNameBAsync(string PartName, object userState) {
            if ((this.GetByPartNameBOperationCompleted == null)) {
                this.GetByPartNameBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByPartNameBOperationCompleted);
            }
            this.InvokeAsync("GetByPartNameB", new object[] {
                        PartName}, this.GetByPartNameBOperationCompleted, userState);
        }
        
        private void OnGetByPartNameBOperationCompleted(object arg) {
            if ((this.GetByPartNameBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByPartNameBCompleted(this, new GetByPartNameBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetById", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetById(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetById", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetByIdAsync(string ClassId, string ObjectId) {
            this.GetByIdAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetByIdAsync(string ClassId, string ObjectId, object userState) {
            if ((this.GetByIdOperationCompleted == null)) {
                this.GetByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByIdOperationCompleted);
            }
            this.InvokeAsync("GetById", new object[] {
                        ClassId,
                        ObjectId}, this.GetByIdOperationCompleted, userState);
        }
        
        private void OnGetByIdOperationCompleted(object arg) {
            if ((this.GetByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetByIdCompleted(this, new GetByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetById2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetById2(string ObjectId) {
            object[] results = this.Invoke("GetById2", new object[] {
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetById2Async(string ObjectId) {
            this.GetById2Async(ObjectId, null);
        }
        
        /// <remarks/>
        public void GetById2Async(string ObjectId, object userState) {
            if ((this.GetById2OperationCompleted == null)) {
                this.GetById2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetById2OperationCompleted);
            }
            this.InvokeAsync("GetById2", new object[] {
                        ObjectId}, this.GetById2OperationCompleted, userState);
        }
        
        private void OnGetById2OperationCompleted(object arg) {
            if ((this.GetById2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetById2Completed(this, new GetById2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChildren", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetChildren(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetChildren", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetChildrenAsync(string ClassId, string ObjectId) {
            this.GetChildrenAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetChildrenAsync(string ClassId, string ObjectId, object userState) {
            if ((this.GetChildrenOperationCompleted == null)) {
                this.GetChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildrenOperationCompleted);
            }
            this.InvokeAsync("GetChildren", new object[] {
                        ClassId,
                        ObjectId}, this.GetChildrenOperationCompleted, userState);
        }
        
        private void OnGetChildrenOperationCompleted(object arg) {
            if ((this.GetChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildrenCompleted(this, new GetChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChildren2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetChildren2(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetChildren2", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetChildren2Async(string ClassId, string ObjectId) {
            this.GetChildren2Async(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetChildren2Async(string ClassId, string ObjectId, object userState) {
            if ((this.GetChildren2OperationCompleted == null)) {
                this.GetChildren2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildren2OperationCompleted);
            }
            this.InvokeAsync("GetChildren2", new object[] {
                        ClassId,
                        ObjectId}, this.GetChildren2OperationCompleted, userState);
        }
        
        private void OnGetChildren2OperationCompleted(object arg) {
            if ((this.GetChildren2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildren2Completed(this, new GetChildren2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChildrenByUnit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetChildrenByUnit(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetChildrenByUnit", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetChildrenByUnitAsync(string ClassId, string ObjectId) {
            this.GetChildrenByUnitAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetChildrenByUnitAsync(string ClassId, string ObjectId, object userState) {
            if ((this.GetChildrenByUnitOperationCompleted == null)) {
                this.GetChildrenByUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChildrenByUnitOperationCompleted);
            }
            this.InvokeAsync("GetChildrenByUnit", new object[] {
                        ClassId,
                        ObjectId}, this.GetChildrenByUnitOperationCompleted, userState);
        }
        
        private void OnGetChildrenByUnitOperationCompleted(object arg) {
            if ((this.GetChildrenByUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChildrenByUnitCompleted(this, new GetChildrenByUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUnitChildren", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetUnitChildren(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetUnitChildren", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetUnitChildrenAsync(string ClassId, string ObjectId) {
            this.GetUnitChildrenAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetUnitChildrenAsync(string ClassId, string ObjectId, object userState) {
            if ((this.GetUnitChildrenOperationCompleted == null)) {
                this.GetUnitChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUnitChildrenOperationCompleted);
            }
            this.InvokeAsync("GetUnitChildren", new object[] {
                        ClassId,
                        ObjectId}, this.GetUnitChildrenOperationCompleted, userState);
        }
        
        private void OnGetUnitChildrenOperationCompleted(object arg) {
            if ((this.GetUnitChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUnitChildrenCompleted(this, new GetUnitChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTypeChildren", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTypeChildren(string ClassId, string ObjectId, string TypeIds) {
            object[] results = this.Invoke("GetTypeChildren", new object[] {
                        ClassId,
                        ObjectId,
                        TypeIds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTypeChildrenAsync(string ClassId, string ObjectId, string TypeIds) {
            this.GetTypeChildrenAsync(ClassId, ObjectId, TypeIds, null);
        }
        
        /// <remarks/>
        public void GetTypeChildrenAsync(string ClassId, string ObjectId, string TypeIds, object userState) {
            if ((this.GetTypeChildrenOperationCompleted == null)) {
                this.GetTypeChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTypeChildrenOperationCompleted);
            }
            this.InvokeAsync("GetTypeChildren", new object[] {
                        ClassId,
                        ObjectId,
                        TypeIds}, this.GetTypeChildrenOperationCompleted, userState);
        }
        
        private void OnGetTypeChildrenOperationCompleted(object arg) {
            if ((this.GetTypeChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTypeChildrenCompleted(this, new GetTypeChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTypeChildrenByDrawingNo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTypeChildrenByDrawingNo(string DrawingNo, string TypeIds) {
            object[] results = this.Invoke("GetTypeChildrenByDrawingNo", new object[] {
                        DrawingNo,
                        TypeIds});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetTypeChildrenByDrawingNoAsync(string DrawingNo, string TypeIds) {
            this.GetTypeChildrenByDrawingNoAsync(DrawingNo, TypeIds, null);
        }
        
        /// <remarks/>
        public void GetTypeChildrenByDrawingNoAsync(string DrawingNo, string TypeIds, object userState) {
            if ((this.GetTypeChildrenByDrawingNoOperationCompleted == null)) {
                this.GetTypeChildrenByDrawingNoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTypeChildrenByDrawingNoOperationCompleted);
            }
            this.InvokeAsync("GetTypeChildrenByDrawingNo", new object[] {
                        DrawingNo,
                        TypeIds}, this.GetTypeChildrenByDrawingNoOperationCompleted, userState);
        }
        
        private void OnGetTypeChildrenByDrawingNoOperationCompleted(object arg) {
            if ((this.GetTypeChildrenByDrawingNoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTypeChildrenByDrawingNoCompleted(this, new GetTypeChildrenByDrawingNoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetParents", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetParents(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetParents", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetParentsAsync(string ClassId, string ObjectId) {
            this.GetParentsAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetParentsAsync(string ClassId, string ObjectId, object userState) {
            if ((this.GetParentsOperationCompleted == null)) {
                this.GetParentsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetParentsOperationCompleted);
            }
            this.InvokeAsync("GetParents", new object[] {
                        ClassId,
                        ObjectId}, this.GetParentsOperationCompleted, userState);
        }
        
        private void OnGetParentsOperationCompleted(object arg) {
            if ((this.GetParentsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetParentsCompleted(this, new GetParentsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemsCount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetItemsCount(string ClassId1, string ObjectId1, string ClassId2, string ObjectId2) {
            object[] results = this.Invoke("GetItemsCount", new object[] {
                        ClassId1,
                        ObjectId1,
                        ClassId2,
                        ObjectId2});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsCountAsync(string ClassId1, string ObjectId1, string ClassId2, string ObjectId2) {
            this.GetItemsCountAsync(ClassId1, ObjectId1, ClassId2, ObjectId2, null);
        }
        
        /// <remarks/>
        public void GetItemsCountAsync(string ClassId1, string ObjectId1, string ClassId2, string ObjectId2, object userState) {
            if ((this.GetItemsCountOperationCompleted == null)) {
                this.GetItemsCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsCountOperationCompleted);
            }
            this.InvokeAsync("GetItemsCount", new object[] {
                        ClassId1,
                        ObjectId1,
                        ClassId2,
                        ObjectId2}, this.GetItemsCountOperationCompleted, userState);
        }
        
        private void OnGetItemsCountOperationCompleted(object arg) {
            if ((this.GetItemsCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsCountCompleted(this, new GetItemsCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDetailsByID", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetDetailsByID(string ClassId, string ObjectId) {
            object[] results = this.Invoke("GetDetailsByID", new object[] {
                        ClassId,
                        ObjectId});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetDetailsByIDAsync(string ClassId, string ObjectId) {
            this.GetDetailsByIDAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void GetDetailsByIDAsync(string ClassId, string ObjectId, object userState) {
            if ((this.GetDetailsByIDOperationCompleted == null)) {
                this.GetDetailsByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDetailsByIDOperationCompleted);
            }
            this.InvokeAsync("GetDetailsByID", new object[] {
                        ClassId,
                        ObjectId}, this.GetDetailsByIDOperationCompleted, userState);
        }
        
        private void OnGetDetailsByIDOperationCompleted(object arg) {
            if ((this.GetDetailsByIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDetailsByIDCompleted(this, new GetDetailsByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemsType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemsType(string DrawingNo) {
            object[] results = this.Invoke("GetItemsType", new object[] {
                        DrawingNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemsTypeAsync(string DrawingNo) {
            this.GetItemsTypeAsync(DrawingNo, null);
        }
        
        /// <remarks/>
        public void GetItemsTypeAsync(string DrawingNo, object userState) {
            if ((this.GetItemsTypeOperationCompleted == null)) {
                this.GetItemsTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemsTypeOperationCompleted);
            }
            this.InvokeAsync("GetItemsType", new object[] {
                        DrawingNo}, this.GetItemsTypeOperationCompleted, userState);
        }
        
        private void OnGetItemsTypeOperationCompleted(object arg) {
            if ((this.GetItemsTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemsTypeCompleted(this, new GetItemsTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPhaseName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetPhaseName(string ObjectId) {
            object[] results = this.Invoke("GetPhaseName", new object[] {
                        ObjectId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetPhaseNameAsync(string ObjectId) {
            this.GetPhaseNameAsync(ObjectId, null);
        }
        
        /// <remarks/>
        public void GetPhaseNameAsync(string ObjectId, object userState) {
            if ((this.GetPhaseNameOperationCompleted == null)) {
                this.GetPhaseNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPhaseNameOperationCompleted);
            }
            this.InvokeAsync("GetPhaseName", new object[] {
                        ObjectId}, this.GetPhaseNameOperationCompleted, userState);
        }
        
        private void OnGetPhaseNameOperationCompleted(object arg) {
            if ((this.GetPhaseNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPhaseNameCompleted(this, new GetPhaseNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLingJianTypeName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetLingJianTypeName(string ObjectId) {
            object[] results = this.Invoke("GetLingJianTypeName", new object[] {
                        ObjectId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetLingJianTypeNameAsync(string ObjectId) {
            this.GetLingJianTypeNameAsync(ObjectId, null);
        }
        
        /// <remarks/>
        public void GetLingJianTypeNameAsync(string ObjectId, object userState) {
            if ((this.GetLingJianTypeNameOperationCompleted == null)) {
                this.GetLingJianTypeNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLingJianTypeNameOperationCompleted);
            }
            this.InvokeAsync("GetLingJianTypeName", new object[] {
                        ObjectId}, this.GetLingJianTypeNameOperationCompleted, userState);
        }
        
        private void OnGetLingJianTypeNameOperationCompleted(object arg) {
            if ((this.GetLingJianTypeNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLingJianTypeNameCompleted(this, new GetLingJianTypeNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetDepName", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDepName(string DepNo) {
            object[] results = this.Invoke("GetDepName", new object[] {
                        DepNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepNameAsync(string DepNo) {
            this.GetDepNameAsync(DepNo, null);
        }
        
        /// <remarks/>
        public void GetDepNameAsync(string DepNo, object userState) {
            if ((this.GetDepNameOperationCompleted == null)) {
                this.GetDepNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepNameOperationCompleted);
            }
            this.InvokeAsync("GetDepName", new object[] {
                        DepNo}, this.GetDepNameOperationCompleted, userState);
        }
        
        private void OnGetDepNameOperationCompleted(object arg) {
            if ((this.GetDepNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepNameCompleted(this, new GetDepNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HasCaiLDE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool HasCaiLDE(string ClassId, string ObjectId) {
            object[] results = this.Invoke("HasCaiLDE", new object[] {
                        ClassId,
                        ObjectId});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void HasCaiLDEAsync(string ClassId, string ObjectId) {
            this.HasCaiLDEAsync(ClassId, ObjectId, null);
        }
        
        /// <remarks/>
        public void HasCaiLDEAsync(string ClassId, string ObjectId, object userState) {
            if ((this.HasCaiLDEOperationCompleted == null)) {
                this.HasCaiLDEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHasCaiLDEOperationCompleted);
            }
            this.InvokeAsync("HasCaiLDE", new object[] {
                        ClassId,
                        ObjectId}, this.HasCaiLDEOperationCompleted, userState);
        }
        
        private void OnHasCaiLDEOperationCompleted(object arg) {
            if ((this.HasCaiLDECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HasCaiLDECompleted(this, new HasCaiLDECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetItemType", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetItemType(string DrawingNo) {
            object[] results = this.Invoke("GetItemType", new object[] {
                        DrawingNo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetItemTypeAsync(string DrawingNo) {
            this.GetItemTypeAsync(DrawingNo, null);
        }
        
        /// <remarks/>
        public void GetItemTypeAsync(string DrawingNo, object userState) {
            if ((this.GetItemTypeOperationCompleted == null)) {
                this.GetItemTypeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetItemTypeOperationCompleted);
            }
            this.InvokeAsync("GetItemType", new object[] {
                        DrawingNo}, this.GetItemTypeOperationCompleted, userState);
        }
        
        private void OnGetItemTypeOperationCompleted(object arg) {
            if ((this.GetItemTypeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetItemTypeCompleted(this, new GetItemTypeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByDrawingNoCompletedEventHandler(object sender, GetByDrawingNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByDrawingNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByDrawingNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByDrawingNoAndLastPhaseCompletedEventHandler(object sender, GetByDrawingNoAndLastPhaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByDrawingNoAndLastPhaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByDrawingNoAndLastPhaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByDrawingNoAndPhaseCompletedEventHandler(object sender, GetByDrawingNoAndPhaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByDrawingNoAndPhaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByDrawingNoAndPhaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByDrawingNo222CompletedEventHandler(object sender, GetByDrawingNo222CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByDrawingNo222CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByDrawingNo222CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByDrawingNoBCompletedEventHandler(object sender, GetByDrawingNoBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByDrawingNoBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByDrawingNoBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByPartNameBCompletedEventHandler(object sender, GetByPartNameBCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByPartNameBCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByPartNameBCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetByIdCompletedEventHandler(object sender, GetByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetById2CompletedEventHandler(object sender, GetById2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetById2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetById2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetChildrenCompletedEventHandler(object sender, GetChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetChildren2CompletedEventHandler(object sender, GetChildren2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildren2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildren2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetChildrenByUnitCompletedEventHandler(object sender, GetChildrenByUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChildrenByUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChildrenByUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUnitChildrenCompletedEventHandler(object sender, GetUnitChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUnitChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUnitChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetTypeChildrenCompletedEventHandler(object sender, GetTypeChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTypeChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTypeChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetTypeChildrenByDrawingNoCompletedEventHandler(object sender, GetTypeChildrenByDrawingNoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTypeChildrenByDrawingNoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTypeChildrenByDrawingNoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetParentsCompletedEventHandler(object sender, GetParentsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetParentsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetParentsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetItemsCountCompletedEventHandler(object sender, GetItemsCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetDetailsByIDCompletedEventHandler(object sender, GetDetailsByIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDetailsByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDetailsByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetItemsTypeCompletedEventHandler(object sender, GetItemsTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemsTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemsTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetPhaseNameCompletedEventHandler(object sender, GetPhaseNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPhaseNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPhaseNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetLingJianTypeNameCompletedEventHandler(object sender, GetLingJianTypeNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLingJianTypeNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLingJianTypeNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetDepNameCompletedEventHandler(object sender, GetDepNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void HasCaiLDECompletedEventHandler(object sender, HasCaiLDECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HasCaiLDECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HasCaiLDECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetItemTypeCompletedEventHandler(object sender, GetItemTypeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetItemTypeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetItemTypeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591