//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mms.Write_Req_Order {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/", ConfigurationName="Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType")]
    public interface CUX_DM_REQ_SYNC_WS_PKG_PortType {
        
        // CODEGEN: 操作 WRITE_REQ_ORDER 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://lm01l115.calt.casc:8008/webservices/SOAProvider/plsql/cux_dm_req_sync_ws_p" +
            "kg/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        mms.Write_Req_Order.WRITE_REQ_ORDERResponse WRITE_REQ_ORDER(mms.Write_Req_Order.WRITE_REQ_ORDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lm01l115.calt.casc:8008/webservices/SOAProvider/plsql/cux_dm_req_sync_ws_p" +
            "kg/", ReplyAction="*")]
        System.Threading.Tasks.Task<mms.Write_Req_Order.WRITE_REQ_ORDERResponse> WRITE_REQ_ORDERAsync(mms.Write_Req_Order.WRITE_REQ_ORDERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/")]
    public partial class SOAHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responsibilityField;
        
        private string respApplicationField;
        
        private string securityGroupField;
        
        private string nLSLanguageField;
        
        private string org_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
                this.RaisePropertyChanged("Responsibility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RespApplication {
            get {
                return this.respApplicationField;
            }
            set {
                this.respApplicationField = value;
                this.RaisePropertyChanged("RespApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecurityGroup {
            get {
                return this.securityGroupField;
            }
            set {
                this.securityGroupField = value;
                this.RaisePropertyChanged("SecurityGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NLSLanguage {
            get {
                return this.nLSLanguageField;
            }
            set {
                this.nLSLanguageField = value;
                this.RaisePropertyChanged("NLSLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
                this.RaisePropertyChanged("Org_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_REQ_SYNC_WS_PKG_RECO25", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
        "eq_order/")]
    public partial class APPSCUX_DM_REQ_SYNC_WS_PKG_RECO25 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTATUSField;
        
        private string eRR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ERR_MSG {
            get {
                return this.eRR_MSGField;
            }
            set {
                this.eRR_MSGField = value;
                this.RaisePropertyChanged("ERR_MSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_REQ_SYNC_WS_PKG_ERRO27", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
        "eq_order/")]
    public partial class APPSCUX_DM_REQ_SYNC_WS_PKG_ERRO27 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> oRG_IDField;
        
        private bool oRG_IDFieldSpecified;
        
        private string sYSTEM_CODEField;
        
        private System.Nullable<decimal> uSER_RQ_IDField;
        
        private bool uSER_RQ_IDFieldSpecified;
        
        private System.Nullable<decimal> uSER_RQ_LINE_IDField;
        
        private bool uSER_RQ_LINE_IDFieldSpecified;
        
        private string eRR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> ORG_ID {
            get {
                return this.oRG_IDField;
            }
            set {
                this.oRG_IDField = value;
                this.RaisePropertyChanged("ORG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORG_IDSpecified {
            get {
                return this.oRG_IDFieldSpecified;
            }
            set {
                this.oRG_IDFieldSpecified = value;
                this.RaisePropertyChanged("ORG_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> USER_RQ_ID {
            get {
                return this.uSER_RQ_IDField;
            }
            set {
                this.uSER_RQ_IDField = value;
                this.RaisePropertyChanged("USER_RQ_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RQ_IDSpecified {
            get {
                return this.uSER_RQ_IDFieldSpecified;
            }
            set {
                this.uSER_RQ_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RQ_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> USER_RQ_LINE_ID {
            get {
                return this.uSER_RQ_LINE_IDField;
            }
            set {
                this.uSER_RQ_LINE_IDField = value;
                this.RaisePropertyChanged("USER_RQ_LINE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RQ_LINE_IDSpecified {
            get {
                return this.uSER_RQ_LINE_IDFieldSpecified;
            }
            set {
                this.uSER_RQ_LINE_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RQ_LINE_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ERR_MSG {
            get {
                return this.eRR_MSGField;
            }
            set {
                this.eRR_MSGField = value;
                this.RaisePropertyChanged("ERR_MSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_REQ_SYNC_WS_PKG_SUM_23", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
        "eq_order/")]
    public partial class APPSCUX_DM_REQ_SYNC_WS_PKG_SUM_23 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sYSTEM_CODEField;
        
        private string tOTAL_FLAGField;
        
        private System.Nullable<decimal> rOW_COUNTField;
        
        private bool rOW_COUNTFieldSpecified;
        
        private System.Nullable<decimal> gROUP_IDField;
        
        private bool gROUP_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string TOTAL_FLAG {
            get {
                return this.tOTAL_FLAGField;
            }
            set {
                this.tOTAL_FLAGField = value;
                this.RaisePropertyChanged("TOTAL_FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> ROW_COUNT {
            get {
                return this.rOW_COUNTField;
            }
            set {
                this.rOW_COUNTField = value;
                this.RaisePropertyChanged("ROW_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ROW_COUNTSpecified {
            get {
                return this.rOW_COUNTFieldSpecified;
            }
            set {
                this.rOW_COUNTFieldSpecified = value;
                this.RaisePropertyChanged("ROW_COUNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> GROUP_ID {
            get {
                return this.gROUP_IDField;
            }
            set {
                this.gROUP_IDField = value;
                this.RaisePropertyChanged("GROUP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROUP_IDSpecified {
            get {
                return this.gROUP_IDFieldSpecified;
            }
            set {
                this.gROUP_IDFieldSpecified = value;
                this.RaisePropertyChanged("GROUP_IDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_REQ_SYNC_WS_PKG_RECO26", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
        "eq_order/")]
    public partial class APPSCUX_DM_REQ_SYNC_WS_PKG_RECO26 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> oRG_IDField;
        
        private bool oRG_IDFieldSpecified;
        
        private string rQ_NUMBERField;
        
        private string uSER_RQ_NUMBERField;
        
        private System.Nullable<decimal> uSER_RQ_IDField;
        
        private bool uSER_RQ_IDFieldSpecified;
        
        private System.Nullable<decimal> uSER_RQ_LINE_IDField;
        
        private bool uSER_RQ_LINE_IDFieldSpecified;
        
        private string rQ_TYPEField;
        
        private string iTEM_CODEField;
        
        private string sPECIAL_REQUESTField;
        
        private System.Nullable<decimal> qUANTITYField;
        
        private bool qUANTITYFieldSpecified;
        
        private System.Nullable<decimal> pIECEField;
        
        private bool pIECEFieldSpecified;
        
        private string dIMENSIONField;
        
        private string mANUFACTURERField;
        
        private System.Nullable<System.DateTime> rQ_DATEField;
        
        private bool rQ_DATEFieldSpecified;
        
        private string uRGENCY_LEVELField;
        
        private string rEQUESTERField;
        
        private string rEQUESTER_PHONEField;
        
        private string iTEM_REVISIONField;
        
        private string uSER_ITEM_DESCRIPTIONField;
        
        private string uNANIMOUS_BATCHField;
        
        private string sECURITY_LEVELField;
        
        private string pROJECTField;
        
        private string pHASEField;
        
        private string bATCHField;
        
        private System.Nullable<decimal> bATCH_QTYField;
        
        private bool bATCH_QTYFieldSpecified;
        
        private string uSAGEField;
        
        private string tASKField;
        
        private string sUBJECTField;
        
        private string cUSTOMER_NAMEField;
        
        private string cUSTOMER_ACCOUNT_NUMBERField;
        
        private string dELIVERY_ADDRESSField;
        
        private string pREPARERField;
        
        private System.Nullable<decimal> sUBMITED_BYField;
        
        private bool sUBMITED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> sUBMISSION_DATEField;
        
        private bool sUBMISSION_DATEFieldSpecified;
        
        private string sYSTEM_CODEField;
        
        private System.Nullable<System.DateTime> tRANSFER_TIMEField;
        
        private bool tRANSFER_TIMEFieldSpecified;
        
        private string cUSTOMER_OF_CREATORField;
        
        private System.Nullable<decimal> gROUP_IDField;
        
        private bool gROUP_IDFieldSpecified;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private System.Nullable<decimal> cREATED_BYField;
        
        private bool cREATED_BYFieldSpecified;
        
        private string aTTRIBUTE_CATEGORYField;
        
        private string aTTRIBUTE1Field;
        
        private string aTTRIBUTE2Field;
        
        private string aTTRIBUTE3Field;
        
        private string aTTRIBUTE4Field;
        
        private string aTTRIBUTE5Field;
        
        private string aTTRIBUTE6Field;
        
        private string aTTRIBUTE7Field;
        
        private string aTTRIBUTE8Field;
        
        private string aTTRIBUTE9Field;
        
        private string aTTRIBUTE10Field;
        
        private string aTTRIBUTE11Field;
        
        private string aTTRIBUTE12Field;
        
        private string aTTRIBUTE13Field;
        
        private string aTTRIBUTE14Field;
        
        private string aTTRIBUTE15Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> ORG_ID {
            get {
                return this.oRG_IDField;
            }
            set {
                this.oRG_IDField = value;
                this.RaisePropertyChanged("ORG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORG_IDSpecified {
            get {
                return this.oRG_IDFieldSpecified;
            }
            set {
                this.oRG_IDFieldSpecified = value;
                this.RaisePropertyChanged("ORG_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string RQ_NUMBER {
            get {
                return this.rQ_NUMBERField;
            }
            set {
                this.rQ_NUMBERField = value;
                this.RaisePropertyChanged("RQ_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string USER_RQ_NUMBER {
            get {
                return this.uSER_RQ_NUMBERField;
            }
            set {
                this.uSER_RQ_NUMBERField = value;
                this.RaisePropertyChanged("USER_RQ_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> USER_RQ_ID {
            get {
                return this.uSER_RQ_IDField;
            }
            set {
                this.uSER_RQ_IDField = value;
                this.RaisePropertyChanged("USER_RQ_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RQ_IDSpecified {
            get {
                return this.uSER_RQ_IDFieldSpecified;
            }
            set {
                this.uSER_RQ_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RQ_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> USER_RQ_LINE_ID {
            get {
                return this.uSER_RQ_LINE_IDField;
            }
            set {
                this.uSER_RQ_LINE_IDField = value;
                this.RaisePropertyChanged("USER_RQ_LINE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RQ_LINE_IDSpecified {
            get {
                return this.uSER_RQ_LINE_IDFieldSpecified;
            }
            set {
                this.uSER_RQ_LINE_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RQ_LINE_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string RQ_TYPE {
            get {
                return this.rQ_TYPEField;
            }
            set {
                this.rQ_TYPEField = value;
                this.RaisePropertyChanged("RQ_TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ITEM_CODE {
            get {
                return this.iTEM_CODEField;
            }
            set {
                this.iTEM_CODEField = value;
                this.RaisePropertyChanged("ITEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string SPECIAL_REQUEST {
            get {
                return this.sPECIAL_REQUESTField;
            }
            set {
                this.sPECIAL_REQUESTField = value;
                this.RaisePropertyChanged("SPECIAL_REQUEST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> QUANTITY {
            get {
                return this.qUANTITYField;
            }
            set {
                this.qUANTITYField = value;
                this.RaisePropertyChanged("QUANTITY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QUANTITYSpecified {
            get {
                return this.qUANTITYFieldSpecified;
            }
            set {
                this.qUANTITYFieldSpecified = value;
                this.RaisePropertyChanged("QUANTITYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> PIECE {
            get {
                return this.pIECEField;
            }
            set {
                this.pIECEField = value;
                this.RaisePropertyChanged("PIECE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PIECESpecified {
            get {
                return this.pIECEFieldSpecified;
            }
            set {
                this.pIECEFieldSpecified = value;
                this.RaisePropertyChanged("PIECESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string DIMENSION {
            get {
                return this.dIMENSIONField;
            }
            set {
                this.dIMENSIONField = value;
                this.RaisePropertyChanged("DIMENSION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string MANUFACTURER {
            get {
                return this.mANUFACTURERField;
            }
            set {
                this.mANUFACTURERField = value;
                this.RaisePropertyChanged("MANUFACTURER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<System.DateTime> RQ_DATE {
            get {
                return this.rQ_DATEField;
            }
            set {
                this.rQ_DATEField = value;
                this.RaisePropertyChanged("RQ_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RQ_DATESpecified {
            get {
                return this.rQ_DATEFieldSpecified;
            }
            set {
                this.rQ_DATEFieldSpecified = value;
                this.RaisePropertyChanged("RQ_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string URGENCY_LEVEL {
            get {
                return this.uRGENCY_LEVELField;
            }
            set {
                this.uRGENCY_LEVELField = value;
                this.RaisePropertyChanged("URGENCY_LEVEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string REQUESTER {
            get {
                return this.rEQUESTERField;
            }
            set {
                this.rEQUESTERField = value;
                this.RaisePropertyChanged("REQUESTER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string REQUESTER_PHONE {
            get {
                return this.rEQUESTER_PHONEField;
            }
            set {
                this.rEQUESTER_PHONEField = value;
                this.RaisePropertyChanged("REQUESTER_PHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string ITEM_REVISION {
            get {
                return this.iTEM_REVISIONField;
            }
            set {
                this.iTEM_REVISIONField = value;
                this.RaisePropertyChanged("ITEM_REVISION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string USER_ITEM_DESCRIPTION {
            get {
                return this.uSER_ITEM_DESCRIPTIONField;
            }
            set {
                this.uSER_ITEM_DESCRIPTIONField = value;
                this.RaisePropertyChanged("USER_ITEM_DESCRIPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string UNANIMOUS_BATCH {
            get {
                return this.uNANIMOUS_BATCHField;
            }
            set {
                this.uNANIMOUS_BATCHField = value;
                this.RaisePropertyChanged("UNANIMOUS_BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string SECURITY_LEVEL {
            get {
                return this.sECURITY_LEVELField;
            }
            set {
                this.sECURITY_LEVELField = value;
                this.RaisePropertyChanged("SECURITY_LEVEL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string PROJECT {
            get {
                return this.pROJECTField;
            }
            set {
                this.pROJECTField = value;
                this.RaisePropertyChanged("PROJECT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string PHASE {
            get {
                return this.pHASEField;
            }
            set {
                this.pHASEField = value;
                this.RaisePropertyChanged("PHASE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string BATCH {
            get {
                return this.bATCHField;
            }
            set {
                this.bATCHField = value;
                this.RaisePropertyChanged("BATCH");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public System.Nullable<decimal> BATCH_QTY {
            get {
                return this.bATCH_QTYField;
            }
            set {
                this.bATCH_QTYField = value;
                this.RaisePropertyChanged("BATCH_QTY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BATCH_QTYSpecified {
            get {
                return this.bATCH_QTYFieldSpecified;
            }
            set {
                this.bATCH_QTYFieldSpecified = value;
                this.RaisePropertyChanged("BATCH_QTYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string USAGE {
            get {
                return this.uSAGEField;
            }
            set {
                this.uSAGEField = value;
                this.RaisePropertyChanged("USAGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string TASK {
            get {
                return this.tASKField;
            }
            set {
                this.tASKField = value;
                this.RaisePropertyChanged("TASK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string SUBJECT {
            get {
                return this.sUBJECTField;
            }
            set {
                this.sUBJECTField = value;
                this.RaisePropertyChanged("SUBJECT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string CUSTOMER_NAME {
            get {
                return this.cUSTOMER_NAMEField;
            }
            set {
                this.cUSTOMER_NAMEField = value;
                this.RaisePropertyChanged("CUSTOMER_NAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string CUSTOMER_ACCOUNT_NUMBER {
            get {
                return this.cUSTOMER_ACCOUNT_NUMBERField;
            }
            set {
                this.cUSTOMER_ACCOUNT_NUMBERField = value;
                this.RaisePropertyChanged("CUSTOMER_ACCOUNT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string DELIVERY_ADDRESS {
            get {
                return this.dELIVERY_ADDRESSField;
            }
            set {
                this.dELIVERY_ADDRESSField = value;
                this.RaisePropertyChanged("DELIVERY_ADDRESS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string PREPARER {
            get {
                return this.pREPARERField;
            }
            set {
                this.pREPARERField = value;
                this.RaisePropertyChanged("PREPARER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> SUBMITED_BY {
            get {
                return this.sUBMITED_BYField;
            }
            set {
                this.sUBMITED_BYField = value;
                this.RaisePropertyChanged("SUBMITED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUBMITED_BYSpecified {
            get {
                return this.sUBMITED_BYFieldSpecified;
            }
            set {
                this.sUBMITED_BYFieldSpecified = value;
                this.RaisePropertyChanged("SUBMITED_BYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<System.DateTime> SUBMISSION_DATE {
            get {
                return this.sUBMISSION_DATEField;
            }
            set {
                this.sUBMISSION_DATEField = value;
                this.RaisePropertyChanged("SUBMISSION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUBMISSION_DATESpecified {
            get {
                return this.sUBMISSION_DATEFieldSpecified;
            }
            set {
                this.sUBMISSION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("SUBMISSION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public System.Nullable<System.DateTime> TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TRANSFER_TIMESpecified {
            get {
                return this.tRANSFER_TIMEFieldSpecified;
            }
            set {
                this.tRANSFER_TIMEFieldSpecified = value;
                this.RaisePropertyChanged("TRANSFER_TIMESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string CUSTOMER_OF_CREATOR {
            get {
                return this.cUSTOMER_OF_CREATORField;
            }
            set {
                this.cUSTOMER_OF_CREATORField = value;
                this.RaisePropertyChanged("CUSTOMER_OF_CREATOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=36)]
        public System.Nullable<decimal> GROUP_ID {
            get {
                return this.gROUP_IDField;
            }
            set {
                this.gROUP_IDField = value;
                this.RaisePropertyChanged("GROUP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROUP_IDSpecified {
            get {
                return this.gROUP_IDFieldSpecified;
            }
            set {
                this.gROUP_IDFieldSpecified = value;
                this.RaisePropertyChanged("GROUP_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=37)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
                this.RaisePropertyChanged("CREATION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("CREATION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=38)]
        public System.Nullable<decimal> CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
                this.RaisePropertyChanged("CREATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATED_BYSpecified {
            get {
                return this.cREATED_BYFieldSpecified;
            }
            set {
                this.cREATED_BYFieldSpecified = value;
                this.RaisePropertyChanged("CREATED_BYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=39)]
        public string ATTRIBUTE_CATEGORY {
            get {
                return this.aTTRIBUTE_CATEGORYField;
            }
            set {
                this.aTTRIBUTE_CATEGORYField = value;
                this.RaisePropertyChanged("ATTRIBUTE_CATEGORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=40)]
        public string ATTRIBUTE1 {
            get {
                return this.aTTRIBUTE1Field;
            }
            set {
                this.aTTRIBUTE1Field = value;
                this.RaisePropertyChanged("ATTRIBUTE1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=41)]
        public string ATTRIBUTE2 {
            get {
                return this.aTTRIBUTE2Field;
            }
            set {
                this.aTTRIBUTE2Field = value;
                this.RaisePropertyChanged("ATTRIBUTE2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=42)]
        public string ATTRIBUTE3 {
            get {
                return this.aTTRIBUTE3Field;
            }
            set {
                this.aTTRIBUTE3Field = value;
                this.RaisePropertyChanged("ATTRIBUTE3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=43)]
        public string ATTRIBUTE4 {
            get {
                return this.aTTRIBUTE4Field;
            }
            set {
                this.aTTRIBUTE4Field = value;
                this.RaisePropertyChanged("ATTRIBUTE4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=44)]
        public string ATTRIBUTE5 {
            get {
                return this.aTTRIBUTE5Field;
            }
            set {
                this.aTTRIBUTE5Field = value;
                this.RaisePropertyChanged("ATTRIBUTE5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=45)]
        public string ATTRIBUTE6 {
            get {
                return this.aTTRIBUTE6Field;
            }
            set {
                this.aTTRIBUTE6Field = value;
                this.RaisePropertyChanged("ATTRIBUTE6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=46)]
        public string ATTRIBUTE7 {
            get {
                return this.aTTRIBUTE7Field;
            }
            set {
                this.aTTRIBUTE7Field = value;
                this.RaisePropertyChanged("ATTRIBUTE7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=47)]
        public string ATTRIBUTE8 {
            get {
                return this.aTTRIBUTE8Field;
            }
            set {
                this.aTTRIBUTE8Field = value;
                this.RaisePropertyChanged("ATTRIBUTE8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=48)]
        public string ATTRIBUTE9 {
            get {
                return this.aTTRIBUTE9Field;
            }
            set {
                this.aTTRIBUTE9Field = value;
                this.RaisePropertyChanged("ATTRIBUTE9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=49)]
        public string ATTRIBUTE10 {
            get {
                return this.aTTRIBUTE10Field;
            }
            set {
                this.aTTRIBUTE10Field = value;
                this.RaisePropertyChanged("ATTRIBUTE10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=50)]
        public string ATTRIBUTE11 {
            get {
                return this.aTTRIBUTE11Field;
            }
            set {
                this.aTTRIBUTE11Field = value;
                this.RaisePropertyChanged("ATTRIBUTE11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=51)]
        public string ATTRIBUTE12 {
            get {
                return this.aTTRIBUTE12Field;
            }
            set {
                this.aTTRIBUTE12Field = value;
                this.RaisePropertyChanged("ATTRIBUTE12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=52)]
        public string ATTRIBUTE13 {
            get {
                return this.aTTRIBUTE13Field;
            }
            set {
                this.aTTRIBUTE13Field = value;
                this.RaisePropertyChanged("ATTRIBUTE13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=53)]
        public string ATTRIBUTE14 {
            get {
                return this.aTTRIBUTE14Field;
            }
            set {
                this.aTTRIBUTE14Field = value;
                this.RaisePropertyChanged("ATTRIBUTE14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=54)]
        public string ATTRIBUTE15 {
            get {
                return this.aTTRIBUTE15Field;
            }
            set {
                this.aTTRIBUTE15Field = value;
                this.RaisePropertyChanged("ATTRIBUTE15");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
        "eq_order/")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APPSCUX_DM_REQ_SYNC_WS_PKG_RECO26[] p_RECORD_INPUTField;
        
        private APPSCUX_DM_REQ_SYNC_WS_PKG_SUM_23 p_SUM_RECORD_INPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("P_RECORD_INPUT_ITEM")]
        public APPSCUX_DM_REQ_SYNC_WS_PKG_RECO26[] P_RECORD_INPUT {
            get {
                return this.p_RECORD_INPUTField;
            }
            set {
                this.p_RECORD_INPUTField = value;
                this.RaisePropertyChanged("P_RECORD_INPUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public APPSCUX_DM_REQ_SYNC_WS_PKG_SUM_23 P_SUM_RECORD_INPUT {
            get {
                return this.p_SUM_RECORD_INPUTField;
            }
            set {
                this.p_SUM_RECORD_INPUTField = value;
                this.RaisePropertyChanged("P_SUM_RECORD_INPUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
        "eq_order/")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APPSCUX_DM_REQ_SYNC_WS_PKG_ERRO27[] x_ERROR_RECORDField;
        
        private APPSCUX_DM_REQ_SYNC_WS_PKG_RECO25 x_RECORD_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("X_ERROR_RECORD_ITEM")]
        public APPSCUX_DM_REQ_SYNC_WS_PKG_ERRO27[] X_ERROR_RECORD {
            get {
                return this.x_ERROR_RECORDField;
            }
            set {
                this.x_ERROR_RECORDField = value;
                this.RaisePropertyChanged("X_ERROR_RECORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public APPSCUX_DM_REQ_SYNC_WS_PKG_RECO25 X_RECORD_RESULT {
            get {
                return this.x_RECORD_RESULTField;
            }
            set {
                this.x_RECORD_RESULTField = value;
                this.RaisePropertyChanged("X_RECORD_RESULT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WRITE_REQ_ORDERRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/")]
        public mms.Write_Req_Order.SOAHeader SOAHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
            "eq_order/", Order=0)]
        public mms.Write_Req_Order.InputParameters InputParameters;
        
        public WRITE_REQ_ORDERRequest() {
        }
        
        public WRITE_REQ_ORDERRequest(mms.Write_Req_Order.SOAHeader SOAHeader, mms.Write_Req_Order.InputParameters InputParameters) {
            this.SOAHeader = SOAHeader;
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WRITE_REQ_ORDERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_req_sync_ws_pkg/write_r" +
            "eq_order/", Order=0)]
        public mms.Write_Req_Order.OutputParameters OutputParameters;
        
        public WRITE_REQ_ORDERResponse() {
        }
        
        public WRITE_REQ_ORDERResponse(mms.Write_Req_Order.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CUX_DM_REQ_SYNC_WS_PKG_PortTypeChannel : mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CUX_DM_REQ_SYNC_WS_PKG_PortTypeClient : System.ServiceModel.ClientBase<mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType>, mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType {
        
        public CUX_DM_REQ_SYNC_WS_PKG_PortTypeClient() {
        }
        
        public CUX_DM_REQ_SYNC_WS_PKG_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CUX_DM_REQ_SYNC_WS_PKG_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUX_DM_REQ_SYNC_WS_PKG_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUX_DM_REQ_SYNC_WS_PKG_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mms.Write_Req_Order.WRITE_REQ_ORDERResponse mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType.WRITE_REQ_ORDER(mms.Write_Req_Order.WRITE_REQ_ORDERRequest request) {
            return base.Channel.WRITE_REQ_ORDER(request);
        }
        
        public mms.Write_Req_Order.OutputParameters WRITE_REQ_ORDER(mms.Write_Req_Order.SOAHeader SOAHeader, mms.Write_Req_Order.InputParameters InputParameters) {
            mms.Write_Req_Order.WRITE_REQ_ORDERRequest inValue = new mms.Write_Req_Order.WRITE_REQ_ORDERRequest();
            inValue.SOAHeader = SOAHeader;
            inValue.InputParameters = InputParameters;
            mms.Write_Req_Order.WRITE_REQ_ORDERResponse retVal = ((mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType)(this)).WRITE_REQ_ORDER(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mms.Write_Req_Order.WRITE_REQ_ORDERResponse> mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType.WRITE_REQ_ORDERAsync(mms.Write_Req_Order.WRITE_REQ_ORDERRequest request) {
            return base.Channel.WRITE_REQ_ORDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<mms.Write_Req_Order.WRITE_REQ_ORDERResponse> WRITE_REQ_ORDERAsync(mms.Write_Req_Order.SOAHeader SOAHeader, mms.Write_Req_Order.InputParameters InputParameters) {
            mms.Write_Req_Order.WRITE_REQ_ORDERRequest inValue = new mms.Write_Req_Order.WRITE_REQ_ORDERRequest();
            inValue.SOAHeader = SOAHeader;
            inValue.InputParameters = InputParameters;
            return ((mms.Write_Req_Order.CUX_DM_REQ_SYNC_WS_PKG_PortType)(this)).WRITE_REQ_ORDERAsync(inValue);
        }
    }
}
