//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mms.Write_Rco_Order {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/", ConfigurationName="Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType")]
    public interface CUX_DM_RCO_SYNC_WS_PKG_PortType {
        
        // CODEGEN: 操作 WRITE_RCO_ORDER 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="http://lm01l115.calt.casc:8008/webservices/SOAProvider/plsql/cux_dm_rco_sync_ws_p" +
            "kg/", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        mms.Write_Rco_Order.WRITE_RCO_ORDERResponse WRITE_RCO_ORDER(mms.Write_Rco_Order.WRITE_RCO_ORDERRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lm01l115.calt.casc:8008/webservices/SOAProvider/plsql/cux_dm_rco_sync_ws_p" +
            "kg/", ReplyAction="*")]
        System.Threading.Tasks.Task<mms.Write_Rco_Order.WRITE_RCO_ORDERResponse> WRITE_RCO_ORDERAsync(mms.Write_Rco_Order.WRITE_RCO_ORDERRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/")]
    public partial class SOAHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string responsibilityField;
        
        private string respApplicationField;
        
        private string securityGroupField;
        
        private string nLSLanguageField;
        
        private string org_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Responsibility {
            get {
                return this.responsibilityField;
            }
            set {
                this.responsibilityField = value;
                this.RaisePropertyChanged("Responsibility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RespApplication {
            get {
                return this.respApplicationField;
            }
            set {
                this.respApplicationField = value;
                this.RaisePropertyChanged("RespApplication");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SecurityGroup {
            get {
                return this.securityGroupField;
            }
            set {
                this.securityGroupField = value;
                this.RaisePropertyChanged("SecurityGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NLSLanguage {
            get {
                return this.nLSLanguageField;
            }
            set {
                this.nLSLanguageField = value;
                this.RaisePropertyChanged("NLSLanguage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Org_Id {
            get {
                return this.org_IdField;
            }
            set {
                this.org_IdField = value;
                this.RaisePropertyChanged("Org_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_RCO_SYNC_WS_PKG_RECO33", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class APPSCUX_DM_RCO_SYNC_WS_PKG_RECO33 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sTATUSField;
        
        private string eRR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ERR_MSG {
            get {
                return this.eRR_MSGField;
            }
            set {
                this.eRR_MSGField = value;
                this.RaisePropertyChanged("ERR_MSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_RCO_SYNC_WS_PKG_ERRO36", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class APPSCUX_DM_RCO_SYNC_WS_PKG_ERRO36 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> oRG_IDField;
        
        private bool oRG_IDFieldSpecified;
        
        private string sYSTEM_CODEField;
        
        private System.Nullable<decimal> uSER_RCO_HEADER_IDField;
        
        private bool uSER_RCO_HEADER_IDFieldSpecified;
        
        private System.Nullable<decimal> uSER_RCO_LINE_IDField;
        
        private bool uSER_RCO_LINE_IDFieldSpecified;
        
        private string eRR_MSGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> ORG_ID {
            get {
                return this.oRG_IDField;
            }
            set {
                this.oRG_IDField = value;
                this.RaisePropertyChanged("ORG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORG_IDSpecified {
            get {
                return this.oRG_IDFieldSpecified;
            }
            set {
                this.oRG_IDFieldSpecified = value;
                this.RaisePropertyChanged("ORG_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> USER_RCO_HEADER_ID {
            get {
                return this.uSER_RCO_HEADER_IDField;
            }
            set {
                this.uSER_RCO_HEADER_IDField = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RCO_HEADER_IDSpecified {
            get {
                return this.uSER_RCO_HEADER_IDFieldSpecified;
            }
            set {
                this.uSER_RCO_HEADER_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> USER_RCO_LINE_ID {
            get {
                return this.uSER_RCO_LINE_IDField;
            }
            set {
                this.uSER_RCO_LINE_IDField = value;
                this.RaisePropertyChanged("USER_RCO_LINE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RCO_LINE_IDSpecified {
            get {
                return this.uSER_RCO_LINE_IDFieldSpecified;
            }
            set {
                this.uSER_RCO_LINE_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RCO_LINE_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ERR_MSG {
            get {
                return this.eRR_MSGField;
            }
            set {
                this.eRR_MSGField = value;
                this.RaisePropertyChanged("ERR_MSG");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_RCO_SYNC_WS_PKG_RECO35", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class APPSCUX_DM_RCO_SYNC_WS_PKG_RECO35 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> uSER_RCO_LINE_IDField;
        
        private bool uSER_RCO_LINE_IDFieldSpecified;
        
        private System.Nullable<decimal> uSER_RCO_HEADER_IDField;
        
        private bool uSER_RCO_HEADER_IDFieldSpecified;
        
        private System.Nullable<decimal> lINE_NUMField;
        
        private bool lINE_NUMFieldSpecified;
        
        private string cOLUMN_CHANGEDField;
        
        private string oRIGINAL_VALUEField;
        
        private string cHANGED_VALUEField;
        
        private string sYSTEM_CODEField;
        
        private System.Nullable<System.DateTime> tRANSFER_TIMEField;
        
        private bool tRANSFER_TIMEFieldSpecified;
        
        private System.Nullable<decimal> gROUP_IDField;
        
        private bool gROUP_IDFieldSpecified;
        
        private string aTTRIBUTE_CATEGORYField;
        
        private string aTTRIBUTE1Field;
        
        private string aTTRIBUTE2Field;
        
        private string aTTRIBUTE3Field;
        
        private string aTTRIBUTE4Field;
        
        private string aTTRIBUTE5Field;
        
        private string aTTRIBUTE6Field;
        
        private string aTTRIBUTE7Field;
        
        private string aTTRIBUTE8Field;
        
        private string aTTRIBUTE9Field;
        
        private string aTTRIBUTE10Field;
        
        private string aTTRIBUTE11Field;
        
        private string aTTRIBUTE12Field;
        
        private string aTTRIBUTE13Field;
        
        private string aTTRIBUTE14Field;
        
        private string aTTRIBUTE15Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> USER_RCO_LINE_ID {
            get {
                return this.uSER_RCO_LINE_IDField;
            }
            set {
                this.uSER_RCO_LINE_IDField = value;
                this.RaisePropertyChanged("USER_RCO_LINE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RCO_LINE_IDSpecified {
            get {
                return this.uSER_RCO_LINE_IDFieldSpecified;
            }
            set {
                this.uSER_RCO_LINE_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RCO_LINE_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> USER_RCO_HEADER_ID {
            get {
                return this.uSER_RCO_HEADER_IDField;
            }
            set {
                this.uSER_RCO_HEADER_IDField = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RCO_HEADER_IDSpecified {
            get {
                return this.uSER_RCO_HEADER_IDFieldSpecified;
            }
            set {
                this.uSER_RCO_HEADER_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> LINE_NUM {
            get {
                return this.lINE_NUMField;
            }
            set {
                this.lINE_NUMField = value;
                this.RaisePropertyChanged("LINE_NUM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LINE_NUMSpecified {
            get {
                return this.lINE_NUMFieldSpecified;
            }
            set {
                this.lINE_NUMFieldSpecified = value;
                this.RaisePropertyChanged("LINE_NUMSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string COLUMN_CHANGED {
            get {
                return this.cOLUMN_CHANGEDField;
            }
            set {
                this.cOLUMN_CHANGEDField = value;
                this.RaisePropertyChanged("COLUMN_CHANGED");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string ORIGINAL_VALUE {
            get {
                return this.oRIGINAL_VALUEField;
            }
            set {
                this.oRIGINAL_VALUEField = value;
                this.RaisePropertyChanged("ORIGINAL_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string CHANGED_VALUE {
            get {
                return this.cHANGED_VALUEField;
            }
            set {
                this.cHANGED_VALUEField = value;
                this.RaisePropertyChanged("CHANGED_VALUE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<System.DateTime> TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TRANSFER_TIMESpecified {
            get {
                return this.tRANSFER_TIMEFieldSpecified;
            }
            set {
                this.tRANSFER_TIMEFieldSpecified = value;
                this.RaisePropertyChanged("TRANSFER_TIMESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> GROUP_ID {
            get {
                return this.gROUP_IDField;
            }
            set {
                this.gROUP_IDField = value;
                this.RaisePropertyChanged("GROUP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROUP_IDSpecified {
            get {
                return this.gROUP_IDFieldSpecified;
            }
            set {
                this.gROUP_IDFieldSpecified = value;
                this.RaisePropertyChanged("GROUP_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string ATTRIBUTE_CATEGORY {
            get {
                return this.aTTRIBUTE_CATEGORYField;
            }
            set {
                this.aTTRIBUTE_CATEGORYField = value;
                this.RaisePropertyChanged("ATTRIBUTE_CATEGORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string ATTRIBUTE1 {
            get {
                return this.aTTRIBUTE1Field;
            }
            set {
                this.aTTRIBUTE1Field = value;
                this.RaisePropertyChanged("ATTRIBUTE1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string ATTRIBUTE2 {
            get {
                return this.aTTRIBUTE2Field;
            }
            set {
                this.aTTRIBUTE2Field = value;
                this.RaisePropertyChanged("ATTRIBUTE2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string ATTRIBUTE3 {
            get {
                return this.aTTRIBUTE3Field;
            }
            set {
                this.aTTRIBUTE3Field = value;
                this.RaisePropertyChanged("ATTRIBUTE3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string ATTRIBUTE4 {
            get {
                return this.aTTRIBUTE4Field;
            }
            set {
                this.aTTRIBUTE4Field = value;
                this.RaisePropertyChanged("ATTRIBUTE4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string ATTRIBUTE5 {
            get {
                return this.aTTRIBUTE5Field;
            }
            set {
                this.aTTRIBUTE5Field = value;
                this.RaisePropertyChanged("ATTRIBUTE5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string ATTRIBUTE6 {
            get {
                return this.aTTRIBUTE6Field;
            }
            set {
                this.aTTRIBUTE6Field = value;
                this.RaisePropertyChanged("ATTRIBUTE6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string ATTRIBUTE7 {
            get {
                return this.aTTRIBUTE7Field;
            }
            set {
                this.aTTRIBUTE7Field = value;
                this.RaisePropertyChanged("ATTRIBUTE7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string ATTRIBUTE8 {
            get {
                return this.aTTRIBUTE8Field;
            }
            set {
                this.aTTRIBUTE8Field = value;
                this.RaisePropertyChanged("ATTRIBUTE8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string ATTRIBUTE9 {
            get {
                return this.aTTRIBUTE9Field;
            }
            set {
                this.aTTRIBUTE9Field = value;
                this.RaisePropertyChanged("ATTRIBUTE9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string ATTRIBUTE10 {
            get {
                return this.aTTRIBUTE10Field;
            }
            set {
                this.aTTRIBUTE10Field = value;
                this.RaisePropertyChanged("ATTRIBUTE10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string ATTRIBUTE11 {
            get {
                return this.aTTRIBUTE11Field;
            }
            set {
                this.aTTRIBUTE11Field = value;
                this.RaisePropertyChanged("ATTRIBUTE11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string ATTRIBUTE12 {
            get {
                return this.aTTRIBUTE12Field;
            }
            set {
                this.aTTRIBUTE12Field = value;
                this.RaisePropertyChanged("ATTRIBUTE12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string ATTRIBUTE13 {
            get {
                return this.aTTRIBUTE13Field;
            }
            set {
                this.aTTRIBUTE13Field = value;
                this.RaisePropertyChanged("ATTRIBUTE13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string ATTRIBUTE14 {
            get {
                return this.aTTRIBUTE14Field;
            }
            set {
                this.aTTRIBUTE14Field = value;
                this.RaisePropertyChanged("ATTRIBUTE14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string ATTRIBUTE15 {
            get {
                return this.aTTRIBUTE15Field;
            }
            set {
                this.aTTRIBUTE15Field = value;
                this.RaisePropertyChanged("ATTRIBUTE15");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_RCO_SYNC_WS_PKG_RECO34", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class APPSCUX_DM_RCO_SYNC_WS_PKG_RECO34 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string rCO_HEADER_NOField;
        
        private System.Nullable<decimal> uSER_RCO_HEADER_IDField;
        
        private bool uSER_RCO_HEADER_IDFieldSpecified;
        
        private string uSER_RCO_HEADER_NOField;
        
        private System.Nullable<decimal> oRG_IDField;
        
        private bool oRG_IDFieldSpecified;
        
        private string rCO_STATUSField;
        
        private System.Nullable<decimal> uSER_RQ_IDField;
        
        private bool uSER_RQ_IDFieldSpecified;
        
        private System.Nullable<decimal> uSER_RQ_LINE_IDField;
        
        private bool uSER_RQ_LINE_IDFieldSpecified;
        
        private string rEASONField;
        
        private string rEQUESTERField;
        
        private string rEQUESTER_PHONEField;
        
        private string pREPARERField;
        
        private System.Nullable<System.DateTime> cREATION_DATEField;
        
        private bool cREATION_DATEFieldSpecified;
        
        private System.Nullable<decimal> cREATED_BYField;
        
        private bool cREATED_BYFieldSpecified;
        
        private string cUSTOMER_OF_CREATORField;
        
        private System.Nullable<decimal> sUBMITTED_BYField;
        
        private bool sUBMITTED_BYFieldSpecified;
        
        private System.Nullable<System.DateTime> sUBMISSION_DATEField;
        
        private bool sUBMISSION_DATEFieldSpecified;
        
        private string cHANGE_OPTIONField;
        
        private string sYSTEM_CODEField;
        
        private System.Nullable<System.DateTime> tRANSFER_TIMEField;
        
        private bool tRANSFER_TIMEFieldSpecified;
        
        private System.Nullable<decimal> gROUP_IDField;
        
        private bool gROUP_IDFieldSpecified;
        
        private string aTTRIBUTE_CATEGORYField;
        
        private string aTTRIBUTE1Field;
        
        private string aTTRIBUTE2Field;
        
        private string aTTRIBUTE3Field;
        
        private string aTTRIBUTE4Field;
        
        private string aTTRIBUTE5Field;
        
        private string aTTRIBUTE6Field;
        
        private string aTTRIBUTE7Field;
        
        private string aTTRIBUTE8Field;
        
        private string aTTRIBUTE9Field;
        
        private string aTTRIBUTE10Field;
        
        private string aTTRIBUTE11Field;
        
        private string aTTRIBUTE12Field;
        
        private string aTTRIBUTE13Field;
        
        private string aTTRIBUTE14Field;
        
        private string aTTRIBUTE15Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string RCO_HEADER_NO {
            get {
                return this.rCO_HEADER_NOField;
            }
            set {
                this.rCO_HEADER_NOField = value;
                this.RaisePropertyChanged("RCO_HEADER_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> USER_RCO_HEADER_ID {
            get {
                return this.uSER_RCO_HEADER_IDField;
            }
            set {
                this.uSER_RCO_HEADER_IDField = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RCO_HEADER_IDSpecified {
            get {
                return this.uSER_RCO_HEADER_IDFieldSpecified;
            }
            set {
                this.uSER_RCO_HEADER_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string USER_RCO_HEADER_NO {
            get {
                return this.uSER_RCO_HEADER_NOField;
            }
            set {
                this.uSER_RCO_HEADER_NOField = value;
                this.RaisePropertyChanged("USER_RCO_HEADER_NO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> ORG_ID {
            get {
                return this.oRG_IDField;
            }
            set {
                this.oRG_IDField = value;
                this.RaisePropertyChanged("ORG_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ORG_IDSpecified {
            get {
                return this.oRG_IDFieldSpecified;
            }
            set {
                this.oRG_IDFieldSpecified = value;
                this.RaisePropertyChanged("ORG_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string RCO_STATUS {
            get {
                return this.rCO_STATUSField;
            }
            set {
                this.rCO_STATUSField = value;
                this.RaisePropertyChanged("RCO_STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> USER_RQ_ID {
            get {
                return this.uSER_RQ_IDField;
            }
            set {
                this.uSER_RQ_IDField = value;
                this.RaisePropertyChanged("USER_RQ_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RQ_IDSpecified {
            get {
                return this.uSER_RQ_IDFieldSpecified;
            }
            set {
                this.uSER_RQ_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RQ_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> USER_RQ_LINE_ID {
            get {
                return this.uSER_RQ_LINE_IDField;
            }
            set {
                this.uSER_RQ_LINE_IDField = value;
                this.RaisePropertyChanged("USER_RQ_LINE_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool USER_RQ_LINE_IDSpecified {
            get {
                return this.uSER_RQ_LINE_IDFieldSpecified;
            }
            set {
                this.uSER_RQ_LINE_IDFieldSpecified = value;
                this.RaisePropertyChanged("USER_RQ_LINE_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string REASON {
            get {
                return this.rEASONField;
            }
            set {
                this.rEASONField = value;
                this.RaisePropertyChanged("REASON");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string REQUESTER {
            get {
                return this.rEQUESTERField;
            }
            set {
                this.rEQUESTERField = value;
                this.RaisePropertyChanged("REQUESTER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string REQUESTER_PHONE {
            get {
                return this.rEQUESTER_PHONEField;
            }
            set {
                this.rEQUESTER_PHONEField = value;
                this.RaisePropertyChanged("REQUESTER_PHONE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string PREPARER {
            get {
                return this.pREPARERField;
            }
            set {
                this.pREPARERField = value;
                this.RaisePropertyChanged("PREPARER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<System.DateTime> CREATION_DATE {
            get {
                return this.cREATION_DATEField;
            }
            set {
                this.cREATION_DATEField = value;
                this.RaisePropertyChanged("CREATION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATION_DATESpecified {
            get {
                return this.cREATION_DATEFieldSpecified;
            }
            set {
                this.cREATION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("CREATION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> CREATED_BY {
            get {
                return this.cREATED_BYField;
            }
            set {
                this.cREATED_BYField = value;
                this.RaisePropertyChanged("CREATED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CREATED_BYSpecified {
            get {
                return this.cREATED_BYFieldSpecified;
            }
            set {
                this.cREATED_BYFieldSpecified = value;
                this.RaisePropertyChanged("CREATED_BYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string CUSTOMER_OF_CREATOR {
            get {
                return this.cUSTOMER_OF_CREATORField;
            }
            set {
                this.cUSTOMER_OF_CREATORField = value;
                this.RaisePropertyChanged("CUSTOMER_OF_CREATOR");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public System.Nullable<decimal> SUBMITTED_BY {
            get {
                return this.sUBMITTED_BYField;
            }
            set {
                this.sUBMITTED_BYField = value;
                this.RaisePropertyChanged("SUBMITTED_BY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUBMITTED_BYSpecified {
            get {
                return this.sUBMITTED_BYFieldSpecified;
            }
            set {
                this.sUBMITTED_BYFieldSpecified = value;
                this.RaisePropertyChanged("SUBMITTED_BYSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<System.DateTime> SUBMISSION_DATE {
            get {
                return this.sUBMISSION_DATEField;
            }
            set {
                this.sUBMISSION_DATEField = value;
                this.RaisePropertyChanged("SUBMISSION_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SUBMISSION_DATESpecified {
            get {
                return this.sUBMISSION_DATEFieldSpecified;
            }
            set {
                this.sUBMISSION_DATEFieldSpecified = value;
                this.RaisePropertyChanged("SUBMISSION_DATESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string CHANGE_OPTION {
            get {
                return this.cHANGE_OPTIONField;
            }
            set {
                this.cHANGE_OPTIONField = value;
                this.RaisePropertyChanged("CHANGE_OPTION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<System.DateTime> TRANSFER_TIME {
            get {
                return this.tRANSFER_TIMEField;
            }
            set {
                this.tRANSFER_TIMEField = value;
                this.RaisePropertyChanged("TRANSFER_TIME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TRANSFER_TIMESpecified {
            get {
                return this.tRANSFER_TIMEFieldSpecified;
            }
            set {
                this.tRANSFER_TIMEFieldSpecified = value;
                this.RaisePropertyChanged("TRANSFER_TIMESpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> GROUP_ID {
            get {
                return this.gROUP_IDField;
            }
            set {
                this.gROUP_IDField = value;
                this.RaisePropertyChanged("GROUP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROUP_IDSpecified {
            get {
                return this.gROUP_IDFieldSpecified;
            }
            set {
                this.gROUP_IDFieldSpecified = value;
                this.RaisePropertyChanged("GROUP_IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string ATTRIBUTE_CATEGORY {
            get {
                return this.aTTRIBUTE_CATEGORYField;
            }
            set {
                this.aTTRIBUTE_CATEGORYField = value;
                this.RaisePropertyChanged("ATTRIBUTE_CATEGORY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string ATTRIBUTE1 {
            get {
                return this.aTTRIBUTE1Field;
            }
            set {
                this.aTTRIBUTE1Field = value;
                this.RaisePropertyChanged("ATTRIBUTE1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string ATTRIBUTE2 {
            get {
                return this.aTTRIBUTE2Field;
            }
            set {
                this.aTTRIBUTE2Field = value;
                this.RaisePropertyChanged("ATTRIBUTE2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string ATTRIBUTE3 {
            get {
                return this.aTTRIBUTE3Field;
            }
            set {
                this.aTTRIBUTE3Field = value;
                this.RaisePropertyChanged("ATTRIBUTE3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string ATTRIBUTE4 {
            get {
                return this.aTTRIBUTE4Field;
            }
            set {
                this.aTTRIBUTE4Field = value;
                this.RaisePropertyChanged("ATTRIBUTE4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string ATTRIBUTE5 {
            get {
                return this.aTTRIBUTE5Field;
            }
            set {
                this.aTTRIBUTE5Field = value;
                this.RaisePropertyChanged("ATTRIBUTE5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=26)]
        public string ATTRIBUTE6 {
            get {
                return this.aTTRIBUTE6Field;
            }
            set {
                this.aTTRIBUTE6Field = value;
                this.RaisePropertyChanged("ATTRIBUTE6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string ATTRIBUTE7 {
            get {
                return this.aTTRIBUTE7Field;
            }
            set {
                this.aTTRIBUTE7Field = value;
                this.RaisePropertyChanged("ATTRIBUTE7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string ATTRIBUTE8 {
            get {
                return this.aTTRIBUTE8Field;
            }
            set {
                this.aTTRIBUTE8Field = value;
                this.RaisePropertyChanged("ATTRIBUTE8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string ATTRIBUTE9 {
            get {
                return this.aTTRIBUTE9Field;
            }
            set {
                this.aTTRIBUTE9Field = value;
                this.RaisePropertyChanged("ATTRIBUTE9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string ATTRIBUTE10 {
            get {
                return this.aTTRIBUTE10Field;
            }
            set {
                this.aTTRIBUTE10Field = value;
                this.RaisePropertyChanged("ATTRIBUTE10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public string ATTRIBUTE11 {
            get {
                return this.aTTRIBUTE11Field;
            }
            set {
                this.aTTRIBUTE11Field = value;
                this.RaisePropertyChanged("ATTRIBUTE11");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string ATTRIBUTE12 {
            get {
                return this.aTTRIBUTE12Field;
            }
            set {
                this.aTTRIBUTE12Field = value;
                this.RaisePropertyChanged("ATTRIBUTE12");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string ATTRIBUTE13 {
            get {
                return this.aTTRIBUTE13Field;
            }
            set {
                this.aTTRIBUTE13Field = value;
                this.RaisePropertyChanged("ATTRIBUTE13");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string ATTRIBUTE14 {
            get {
                return this.aTTRIBUTE14Field;
            }
            set {
                this.aTTRIBUTE14Field = value;
                this.RaisePropertyChanged("ATTRIBUTE14");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string ATTRIBUTE15 {
            get {
                return this.aTTRIBUTE15Field;
            }
            set {
                this.aTTRIBUTE15Field = value;
                this.RaisePropertyChanged("ATTRIBUTE15");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="APPS.CUX_DM_RCO_SYNC_WS_PKG_SUM_29", Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class APPSCUX_DM_RCO_SYNC_WS_PKG_SUM_29 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sYSTEM_CODEField;
        
        private string tOTAL_FLAGField;
        
        private System.Nullable<decimal> rOW_COUNTField;
        
        private bool rOW_COUNTFieldSpecified;
        
        private System.Nullable<decimal> gROUP_IDField;
        
        private bool gROUP_IDFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SYSTEM_CODE {
            get {
                return this.sYSTEM_CODEField;
            }
            set {
                this.sYSTEM_CODEField = value;
                this.RaisePropertyChanged("SYSTEM_CODE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string TOTAL_FLAG {
            get {
                return this.tOTAL_FLAGField;
            }
            set {
                this.tOTAL_FLAGField = value;
                this.RaisePropertyChanged("TOTAL_FLAG");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<decimal> ROW_COUNT {
            get {
                return this.rOW_COUNTField;
            }
            set {
                this.rOW_COUNTField = value;
                this.RaisePropertyChanged("ROW_COUNT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ROW_COUNTSpecified {
            get {
                return this.rOW_COUNTFieldSpecified;
            }
            set {
                this.rOW_COUNTFieldSpecified = value;
                this.RaisePropertyChanged("ROW_COUNTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<decimal> GROUP_ID {
            get {
                return this.gROUP_IDField;
            }
            set {
                this.gROUP_IDField = value;
                this.RaisePropertyChanged("GROUP_ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GROUP_IDSpecified {
            get {
                return this.gROUP_IDFieldSpecified;
            }
            set {
                this.gROUP_IDFieldSpecified = value;
                this.RaisePropertyChanged("GROUP_IDSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class InputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APPSCUX_DM_RCO_SYNC_WS_PKG_SUM_29 p_SUM_RECORD_INPUTField;
        
        private APPSCUX_DM_RCO_SYNC_WS_PKG_RECO34[] p_HEADER_INPUTField;
        
        private APPSCUX_DM_RCO_SYNC_WS_PKG_RECO35[] p_LINE_INPUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public APPSCUX_DM_RCO_SYNC_WS_PKG_SUM_29 P_SUM_RECORD_INPUT {
            get {
                return this.p_SUM_RECORD_INPUTField;
            }
            set {
                this.p_SUM_RECORD_INPUTField = value;
                this.RaisePropertyChanged("P_SUM_RECORD_INPUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("P_HEADER_INPUT_ITEM")]
        public APPSCUX_DM_RCO_SYNC_WS_PKG_RECO34[] P_HEADER_INPUT {
            get {
                return this.p_HEADER_INPUTField;
            }
            set {
                this.p_HEADER_INPUTField = value;
                this.RaisePropertyChanged("P_HEADER_INPUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("P_LINE_INPUT_ITEM")]
        public APPSCUX_DM_RCO_SYNC_WS_PKG_RECO35[] P_LINE_INPUT {
            get {
                return this.p_LINE_INPUTField;
            }
            set {
                this.p_LINE_INPUTField = value;
                this.RaisePropertyChanged("P_LINE_INPUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
        "co_order/")]
    public partial class OutputParameters : object, System.ComponentModel.INotifyPropertyChanged {
        
        private APPSCUX_DM_RCO_SYNC_WS_PKG_ERRO36[] x_ERROR_RECORDField;
        
        private APPSCUX_DM_RCO_SYNC_WS_PKG_RECO33 x_RECORD_RESULTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("X_ERROR_RECORD_ITEM")]
        public APPSCUX_DM_RCO_SYNC_WS_PKG_ERRO36[] X_ERROR_RECORD {
            get {
                return this.x_ERROR_RECORDField;
            }
            set {
                this.x_ERROR_RECORDField = value;
                this.RaisePropertyChanged("X_ERROR_RECORD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public APPSCUX_DM_RCO_SYNC_WS_PKG_RECO33 X_RECORD_RESULT {
            get {
                return this.x_RECORD_RESULTField;
            }
            set {
                this.x_RECORD_RESULTField = value;
                this.RaisePropertyChanged("X_RECORD_RESULT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WRITE_RCO_ORDERRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/")]
        public mms.Write_Rco_Order.SOAHeader SOAHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
            "co_order/", Order=0)]
        public mms.Write_Rco_Order.InputParameters InputParameters;
        
        public WRITE_RCO_ORDERRequest() {
        }
        
        public WRITE_RCO_ORDERRequest(mms.Write_Rco_Order.SOAHeader SOAHeader, mms.Write_Rco_Order.InputParameters InputParameters) {
            this.SOAHeader = SOAHeader;
            this.InputParameters = InputParameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WRITE_RCO_ORDERResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://xmlns.oracle.com/apps/cux/soaprovider/plsql/cux_dm_rco_sync_ws_pkg/write_r" +
            "co_order/", Order=0)]
        public mms.Write_Rco_Order.OutputParameters OutputParameters;
        
        public WRITE_RCO_ORDERResponse() {
        }
        
        public WRITE_RCO_ORDERResponse(mms.Write_Rco_Order.OutputParameters OutputParameters) {
            this.OutputParameters = OutputParameters;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CUX_DM_RCO_SYNC_WS_PKG_PortTypeChannel : mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CUX_DM_RCO_SYNC_WS_PKG_PortTypeClient : System.ServiceModel.ClientBase<mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType>, mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType {
        
        public CUX_DM_RCO_SYNC_WS_PKG_PortTypeClient() {
        }
        
        public CUX_DM_RCO_SYNC_WS_PKG_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CUX_DM_RCO_SYNC_WS_PKG_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUX_DM_RCO_SYNC_WS_PKG_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUX_DM_RCO_SYNC_WS_PKG_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mms.Write_Rco_Order.WRITE_RCO_ORDERResponse mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType.WRITE_RCO_ORDER(mms.Write_Rco_Order.WRITE_RCO_ORDERRequest request) {
            return base.Channel.WRITE_RCO_ORDER(request);
        }
        
        public mms.Write_Rco_Order.OutputParameters WRITE_RCO_ORDER(mms.Write_Rco_Order.SOAHeader SOAHeader, mms.Write_Rco_Order.InputParameters InputParameters) {
            mms.Write_Rco_Order.WRITE_RCO_ORDERRequest inValue = new mms.Write_Rco_Order.WRITE_RCO_ORDERRequest();
            inValue.SOAHeader = SOAHeader;
            inValue.InputParameters = InputParameters;
            mms.Write_Rco_Order.WRITE_RCO_ORDERResponse retVal = ((mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType)(this)).WRITE_RCO_ORDER(inValue);
            return retVal.OutputParameters;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mms.Write_Rco_Order.WRITE_RCO_ORDERResponse> mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType.WRITE_RCO_ORDERAsync(mms.Write_Rco_Order.WRITE_RCO_ORDERRequest request) {
            return base.Channel.WRITE_RCO_ORDERAsync(request);
        }
        
        public System.Threading.Tasks.Task<mms.Write_Rco_Order.WRITE_RCO_ORDERResponse> WRITE_RCO_ORDERAsync(mms.Write_Rco_Order.SOAHeader SOAHeader, mms.Write_Rco_Order.InputParameters InputParameters) {
            mms.Write_Rco_Order.WRITE_RCO_ORDERRequest inValue = new mms.Write_Rco_Order.WRITE_RCO_ORDERRequest();
            inValue.SOAHeader = SOAHeader;
            inValue.InputParameters = InputParameters;
            return ((mms.Write_Rco_Order.CUX_DM_RCO_SYNC_WS_PKG_PortType)(this)).WRITE_RCO_ORDERAsync(inValue);
        }
    }
}
