//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace mms.ReturnApplyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ReturnApplyService/", ConfigurationName="ReturnApplyService.ReturnApplyServicePortType")]
    public interface ReturnApplyServicePortType {
        
        // CODEGEN: 消息 returnApplyInfoRequest 的包装命名空间(http://ReturnApplyService/xsd)以后生成的消息协定与默认值(http://ReturnApplyService/)不匹配
        [System.ServiceModel.OperationContractAttribute(Action="urn:returnApplyInfo", ReplyAction="urn:returnApplyInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutStockResponseBaseInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutStockParamVdefdocInfo))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OutStockParamBaseInfo))]
        mms.ReturnApplyService.returnApplyInfoResponse returnApplyInfo(mms.ReturnApplyService.returnApplyInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:returnApplyInfo", ReplyAction="urn:returnApplyInfoResponse")]
        System.Threading.Tasks.Task<mms.ReturnApplyService.returnApplyInfoResponse> returnApplyInfoAsync(mms.ReturnApplyService.returnApplyInfoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://returnapply.requestinfo.outstock.htyy.nc/xsd")]
    public partial class ReturnApplyParam : OutStockParamBaseInfo {
        
        private ReturnApplyParamBillinfo[] returnApplyRequestBillinfoField;
        
        private System.Nullable<int> row_CountField;
        
        private bool row_CountFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("returnApplyRequestBillinfo", IsNullable=true, Order=0)]
        public ReturnApplyParamBillinfo[] returnApplyRequestBillinfo {
            get {
                return this.returnApplyRequestBillinfoField;
            }
            set {
                this.returnApplyRequestBillinfoField = value;
                this.RaisePropertyChanged("returnApplyRequestBillinfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<int> row_Count {
            get {
                return this.row_CountField;
            }
            set {
                this.row_CountField = value;
                this.RaisePropertyChanged("row_Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool row_CountSpecified {
            get {
                return this.row_CountFieldSpecified;
            }
            set {
                this.row_CountFieldSpecified = value;
                this.RaisePropertyChanged("row_CountSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://returnapply.requestinfo.outstock.htyy.nc/xsd")]
    public partial class ReturnApplyParamBillinfo : OutStockParamVdefdocInfo {
        
        private string cgeneralbidField;
        
        private string distraddressField;
        
        private string accountcorpField;
        
        private string billnoField;
        
        private string replacecorpField;
        
        private System.Nullable<decimal> itemnumField;
        
        private bool itemnumFieldSpecified;
        
        private string replacedeptField;
        
        private string pk_ZrrField;
        
        private string returnnoteField;
        
        private string billdateField;
        
        private string invcodeField;
        
        private string cgeneralhidField;
        
        private string jc_PhoneField;
        
        private System.Nullable<decimal> nnumField;
        
        private bool nnumFieldSpecified;
        
        private string replaceuserField;
        
        private string accountmodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string cgeneralbid {
            get {
                return this.cgeneralbidField;
            }
            set {
                this.cgeneralbidField = value;
                this.RaisePropertyChanged("cgeneralbid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string distraddress {
            get {
                return this.distraddressField;
            }
            set {
                this.distraddressField = value;
                this.RaisePropertyChanged("distraddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string accountcorp {
            get {
                return this.accountcorpField;
            }
            set {
                this.accountcorpField = value;
                this.RaisePropertyChanged("accountcorp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string billno {
            get {
                return this.billnoField;
            }
            set {
                this.billnoField = value;
                this.RaisePropertyChanged("billno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string replacecorp {
            get {
                return this.replacecorpField;
            }
            set {
                this.replacecorpField = value;
                this.RaisePropertyChanged("replacecorp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> itemnum {
            get {
                return this.itemnumField;
            }
            set {
                this.itemnumField = value;
                this.RaisePropertyChanged("itemnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool itemnumSpecified {
            get {
                return this.itemnumFieldSpecified;
            }
            set {
                this.itemnumFieldSpecified = value;
                this.RaisePropertyChanged("itemnumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string replacedept {
            get {
                return this.replacedeptField;
            }
            set {
                this.replacedeptField = value;
                this.RaisePropertyChanged("replacedept");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string pk_Zrr {
            get {
                return this.pk_ZrrField;
            }
            set {
                this.pk_ZrrField = value;
                this.RaisePropertyChanged("pk_Zrr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string returnnote {
            get {
                return this.returnnoteField;
            }
            set {
                this.returnnoteField = value;
                this.RaisePropertyChanged("returnnote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string billdate {
            get {
                return this.billdateField;
            }
            set {
                this.billdateField = value;
                this.RaisePropertyChanged("billdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string invcode {
            get {
                return this.invcodeField;
            }
            set {
                this.invcodeField = value;
                this.RaisePropertyChanged("invcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string cgeneralhid {
            get {
                return this.cgeneralhidField;
            }
            set {
                this.cgeneralhidField = value;
                this.RaisePropertyChanged("cgeneralhid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string jc_Phone {
            get {
                return this.jc_PhoneField;
            }
            set {
                this.jc_PhoneField = value;
                this.RaisePropertyChanged("jc_Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> nnum {
            get {
                return this.nnumField;
            }
            set {
                this.nnumField = value;
                this.RaisePropertyChanged("nnum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nnumSpecified {
            get {
                return this.nnumFieldSpecified;
            }
            set {
                this.nnumFieldSpecified = value;
                this.RaisePropertyChanged("nnumSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string replaceuser {
            get {
                return this.replaceuserField;
            }
            set {
                this.replaceuserField = value;
                this.RaisePropertyChanged("replaceuser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string accountmode {
            get {
                return this.accountmodeField;
            }
            set {
                this.accountmodeField = value;
                this.RaisePropertyChanged("accountmode");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnApplyParamBillinfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://requestinfo.outstock.htyy.nc/xsd")]
    public partial class OutStockParamVdefdocInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> vdefdou9Field;
        
        private bool vdefdou9FieldSpecified;
        
        private System.Nullable<decimal> vdefdou8Field;
        
        private bool vdefdou8FieldSpecified;
        
        private string userSysBillBidField;
        
        private string vdefstr1Field;
        
        private System.Nullable<decimal> vdefdou7Field;
        
        private bool vdefdou7FieldSpecified;
        
        private System.Nullable<decimal> vdefdou6Field;
        
        private bool vdefdou6FieldSpecified;
        
        private System.Nullable<decimal> vdefdou5Field;
        
        private bool vdefdou5FieldSpecified;
        
        private System.Nullable<decimal> vdefdou4Field;
        
        private bool vdefdou4FieldSpecified;
        
        private System.Nullable<decimal> vdefdou3Field;
        
        private bool vdefdou3FieldSpecified;
        
        private string vdefstr10Field;
        
        private System.Nullable<decimal> vdefdou2Field;
        
        private bool vdefdou2FieldSpecified;
        
        private System.Nullable<decimal> vdefdou1Field;
        
        private bool vdefdou1FieldSpecified;
        
        private System.Nullable<decimal> vdefdou10Field;
        
        private bool vdefdou10FieldSpecified;
        
        private string userSysBillHidField;
        
        private string vdefstr7Field;
        
        private string vdefstr6Field;
        
        private string vdefstr9Field;
        
        private string vdefstr8Field;
        
        private string vdefstr3Field;
        
        private string vdefstr2Field;
        
        private string vdefstr5Field;
        
        private string vdefstr4Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<decimal> vdefdou9 {
            get {
                return this.vdefdou9Field;
            }
            set {
                this.vdefdou9Field = value;
                this.RaisePropertyChanged("vdefdou9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou9Specified {
            get {
                return this.vdefdou9FieldSpecified;
            }
            set {
                this.vdefdou9FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou9Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> vdefdou8 {
            get {
                return this.vdefdou8Field;
            }
            set {
                this.vdefdou8Field = value;
                this.RaisePropertyChanged("vdefdou8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou8Specified {
            get {
                return this.vdefdou8FieldSpecified;
            }
            set {
                this.vdefdou8FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou8Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string userSysBillBid {
            get {
                return this.userSysBillBidField;
            }
            set {
                this.userSysBillBidField = value;
                this.RaisePropertyChanged("userSysBillBid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string vdefstr1 {
            get {
                return this.vdefstr1Field;
            }
            set {
                this.vdefstr1Field = value;
                this.RaisePropertyChanged("vdefstr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> vdefdou7 {
            get {
                return this.vdefdou7Field;
            }
            set {
                this.vdefdou7Field = value;
                this.RaisePropertyChanged("vdefdou7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou7Specified {
            get {
                return this.vdefdou7FieldSpecified;
            }
            set {
                this.vdefdou7FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou7Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> vdefdou6 {
            get {
                return this.vdefdou6Field;
            }
            set {
                this.vdefdou6Field = value;
                this.RaisePropertyChanged("vdefdou6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou6Specified {
            get {
                return this.vdefdou6FieldSpecified;
            }
            set {
                this.vdefdou6FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou6Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> vdefdou5 {
            get {
                return this.vdefdou5Field;
            }
            set {
                this.vdefdou5Field = value;
                this.RaisePropertyChanged("vdefdou5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou5Specified {
            get {
                return this.vdefdou5FieldSpecified;
            }
            set {
                this.vdefdou5FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou5Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> vdefdou4 {
            get {
                return this.vdefdou4Field;
            }
            set {
                this.vdefdou4Field = value;
                this.RaisePropertyChanged("vdefdou4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou4Specified {
            get {
                return this.vdefdou4FieldSpecified;
            }
            set {
                this.vdefdou4FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<decimal> vdefdou3 {
            get {
                return this.vdefdou3Field;
            }
            set {
                this.vdefdou3Field = value;
                this.RaisePropertyChanged("vdefdou3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou3Specified {
            get {
                return this.vdefdou3FieldSpecified;
            }
            set {
                this.vdefdou3FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string vdefstr10 {
            get {
                return this.vdefstr10Field;
            }
            set {
                this.vdefstr10Field = value;
                this.RaisePropertyChanged("vdefstr10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> vdefdou2 {
            get {
                return this.vdefdou2Field;
            }
            set {
                this.vdefdou2Field = value;
                this.RaisePropertyChanged("vdefdou2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou2Specified {
            get {
                return this.vdefdou2FieldSpecified;
            }
            set {
                this.vdefdou2FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> vdefdou1 {
            get {
                return this.vdefdou1Field;
            }
            set {
                this.vdefdou1Field = value;
                this.RaisePropertyChanged("vdefdou1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou1Specified {
            get {
                return this.vdefdou1FieldSpecified;
            }
            set {
                this.vdefdou1FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> vdefdou10 {
            get {
                return this.vdefdou10Field;
            }
            set {
                this.vdefdou10Field = value;
                this.RaisePropertyChanged("vdefdou10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefdou10Specified {
            get {
                return this.vdefdou10FieldSpecified;
            }
            set {
                this.vdefdou10FieldSpecified = value;
                this.RaisePropertyChanged("vdefdou10Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string userSysBillHid {
            get {
                return this.userSysBillHidField;
            }
            set {
                this.userSysBillHidField = value;
                this.RaisePropertyChanged("userSysBillHid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string vdefstr7 {
            get {
                return this.vdefstr7Field;
            }
            set {
                this.vdefstr7Field = value;
                this.RaisePropertyChanged("vdefstr7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string vdefstr6 {
            get {
                return this.vdefstr6Field;
            }
            set {
                this.vdefstr6Field = value;
                this.RaisePropertyChanged("vdefstr6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string vdefstr9 {
            get {
                return this.vdefstr9Field;
            }
            set {
                this.vdefstr9Field = value;
                this.RaisePropertyChanged("vdefstr9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string vdefstr8 {
            get {
                return this.vdefstr8Field;
            }
            set {
                this.vdefstr8Field = value;
                this.RaisePropertyChanged("vdefstr8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string vdefstr3 {
            get {
                return this.vdefstr3Field;
            }
            set {
                this.vdefstr3Field = value;
                this.RaisePropertyChanged("vdefstr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public string vdefstr2 {
            get {
                return this.vdefstr2Field;
            }
            set {
                this.vdefstr2Field = value;
                this.RaisePropertyChanged("vdefstr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string vdefstr5 {
            get {
                return this.vdefstr5Field;
            }
            set {
                this.vdefstr5Field = value;
                this.RaisePropertyChanged("vdefstr5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string vdefstr4 {
            get {
                return this.vdefstr4Field;
            }
            set {
                this.vdefstr4Field = value;
                this.RaisePropertyChanged("vdefstr4");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnApplyResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://responseinfo.outstock.htyy.nc/xsd")]
    public partial class OutStockResponseBaseInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vdefString5Field;
        
        private string vdefString4Field;
        
        private string vdefString7Field;
        
        private string vdefString6Field;
        
        private string vdefString1Field;
        
        private System.Nullable<decimal> vdefDouble8Field;
        
        private bool vdefDouble8FieldSpecified;
        
        private string vdefString3Field;
        
        private System.Nullable<decimal> vdefDouble9Field;
        
        private bool vdefDouble9FieldSpecified;
        
        private string vdefString2Field;
        
        private System.Nullable<decimal> vdefDouble6Field;
        
        private bool vdefDouble6FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble7Field;
        
        private bool vdefDouble7FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble4Field;
        
        private bool vdefDouble4FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble5Field;
        
        private bool vdefDouble5FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble2Field;
        
        private bool vdefDouble2FieldSpecified;
        
        private string vdefString9Field;
        
        private System.Nullable<decimal> vdefDouble3Field;
        
        private bool vdefDouble3FieldSpecified;
        
        private string vdefString8Field;
        
        private string returnResultField;
        
        private System.Nullable<decimal> vdefDouble1Field;
        
        private bool vdefDouble1FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble10Field;
        
        private bool vdefDouble10FieldSpecified;
        
        private string errorInfoField;
        
        private string vdefString10Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string vdefString5 {
            get {
                return this.vdefString5Field;
            }
            set {
                this.vdefString5Field = value;
                this.RaisePropertyChanged("vdefString5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string vdefString4 {
            get {
                return this.vdefString4Field;
            }
            set {
                this.vdefString4Field = value;
                this.RaisePropertyChanged("vdefString4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string vdefString7 {
            get {
                return this.vdefString7Field;
            }
            set {
                this.vdefString7Field = value;
                this.RaisePropertyChanged("vdefString7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string vdefString6 {
            get {
                return this.vdefString6Field;
            }
            set {
                this.vdefString6Field = value;
                this.RaisePropertyChanged("vdefString6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string vdefString1 {
            get {
                return this.vdefString1Field;
            }
            set {
                this.vdefString1Field = value;
                this.RaisePropertyChanged("vdefString1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> vdefDouble8 {
            get {
                return this.vdefDouble8Field;
            }
            set {
                this.vdefDouble8Field = value;
                this.RaisePropertyChanged("vdefDouble8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble8Specified {
            get {
                return this.vdefDouble8FieldSpecified;
            }
            set {
                this.vdefDouble8FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble8Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string vdefString3 {
            get {
                return this.vdefString3Field;
            }
            set {
                this.vdefString3Field = value;
                this.RaisePropertyChanged("vdefString3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public System.Nullable<decimal> vdefDouble9 {
            get {
                return this.vdefDouble9Field;
            }
            set {
                this.vdefDouble9Field = value;
                this.RaisePropertyChanged("vdefDouble9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble9Specified {
            get {
                return this.vdefDouble9FieldSpecified;
            }
            set {
                this.vdefDouble9FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble9Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string vdefString2 {
            get {
                return this.vdefString2Field;
            }
            set {
                this.vdefString2Field = value;
                this.RaisePropertyChanged("vdefString2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> vdefDouble6 {
            get {
                return this.vdefDouble6Field;
            }
            set {
                this.vdefDouble6Field = value;
                this.RaisePropertyChanged("vdefDouble6");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble6Specified {
            get {
                return this.vdefDouble6FieldSpecified;
            }
            set {
                this.vdefDouble6FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble6Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<decimal> vdefDouble7 {
            get {
                return this.vdefDouble7Field;
            }
            set {
                this.vdefDouble7Field = value;
                this.RaisePropertyChanged("vdefDouble7");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble7Specified {
            get {
                return this.vdefDouble7FieldSpecified;
            }
            set {
                this.vdefDouble7FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble7Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<decimal> vdefDouble4 {
            get {
                return this.vdefDouble4Field;
            }
            set {
                this.vdefDouble4Field = value;
                this.RaisePropertyChanged("vdefDouble4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble4Specified {
            get {
                return this.vdefDouble4FieldSpecified;
            }
            set {
                this.vdefDouble4FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble4Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<decimal> vdefDouble5 {
            get {
                return this.vdefDouble5Field;
            }
            set {
                this.vdefDouble5Field = value;
                this.RaisePropertyChanged("vdefDouble5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble5Specified {
            get {
                return this.vdefDouble5FieldSpecified;
            }
            set {
                this.vdefDouble5FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble5Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public System.Nullable<decimal> vdefDouble2 {
            get {
                return this.vdefDouble2Field;
            }
            set {
                this.vdefDouble2Field = value;
                this.RaisePropertyChanged("vdefDouble2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble2Specified {
            get {
                return this.vdefDouble2FieldSpecified;
            }
            set {
                this.vdefDouble2FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string vdefString9 {
            get {
                return this.vdefString9Field;
            }
            set {
                this.vdefString9Field = value;
                this.RaisePropertyChanged("vdefString9");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public System.Nullable<decimal> vdefDouble3 {
            get {
                return this.vdefDouble3Field;
            }
            set {
                this.vdefDouble3Field = value;
                this.RaisePropertyChanged("vdefDouble3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble3Specified {
            get {
                return this.vdefDouble3FieldSpecified;
            }
            set {
                this.vdefDouble3FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string vdefString8 {
            get {
                return this.vdefString8Field;
            }
            set {
                this.vdefString8Field = value;
                this.RaisePropertyChanged("vdefString8");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string returnResult {
            get {
                return this.returnResultField;
            }
            set {
                this.returnResultField = value;
                this.RaisePropertyChanged("returnResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<decimal> vdefDouble1 {
            get {
                return this.vdefDouble1Field;
            }
            set {
                this.vdefDouble1Field = value;
                this.RaisePropertyChanged("vdefDouble1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble1Specified {
            get {
                return this.vdefDouble1FieldSpecified;
            }
            set {
                this.vdefDouble1FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<decimal> vdefDouble10 {
            get {
                return this.vdefDouble10Field;
            }
            set {
                this.vdefDouble10Field = value;
                this.RaisePropertyChanged("vdefDouble10");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble10Specified {
            get {
                return this.vdefDouble10FieldSpecified;
            }
            set {
                this.vdefDouble10FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble10Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string errorInfo {
            get {
                return this.errorInfoField;
            }
            set {
                this.errorInfoField = value;
                this.RaisePropertyChanged("errorInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string vdefString10 {
            get {
                return this.vdefString10Field;
            }
            set {
                this.vdefString10Field = value;
                this.RaisePropertyChanged("vdefString10");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://returnapply.responseinfo.outstock.htyy.nc/xsd")]
    public partial class ReturnApplyResponse : OutStockResponseBaseInfo {
        
        private string billNoField;
        
        private string userSysBillBidField;
        
        private string userSysBillHidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string billNo {
            get {
                return this.billNoField;
            }
            set {
                this.billNoField = value;
                this.RaisePropertyChanged("billNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string userSysBillBid {
            get {
                return this.userSysBillBidField;
            }
            set {
                this.userSysBillBidField = value;
                this.RaisePropertyChanged("userSysBillBid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string userSysBillHid {
            get {
                return this.userSysBillHidField;
            }
            set {
                this.userSysBillHidField = value;
                this.RaisePropertyChanged("userSysBillHid");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReturnApplyParam))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://requestinfo.outstock.htyy.nc/xsd")]
    public partial class OutStockParamBaseInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string vdefString1Field;
        
        private string vdefString3Field;
        
        private string vdefString2Field;
        
        private string customerSysPortField;
        
        private System.Nullable<decimal> vdefDouble2Field;
        
        private bool vdefDouble2FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble3Field;
        
        private bool vdefDouble3FieldSpecified;
        
        private System.Nullable<decimal> vdefDouble1Field;
        
        private bool vdefDouble1FieldSpecified;
        
        private string customerSysCodeField;
        
        private string customerSyspwdField;
        
        private System.Nullable<int> vdefInteger3Field;
        
        private bool vdefInteger3FieldSpecified;
        
        private string customerSysIpField;
        
        private System.Nullable<int> vdefInteger1Field;
        
        private bool vdefInteger1FieldSpecified;
        
        private System.Nullable<int> vdefInteger2Field;
        
        private bool vdefInteger2FieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string vdefString1 {
            get {
                return this.vdefString1Field;
            }
            set {
                this.vdefString1Field = value;
                this.RaisePropertyChanged("vdefString1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string vdefString3 {
            get {
                return this.vdefString3Field;
            }
            set {
                this.vdefString3Field = value;
                this.RaisePropertyChanged("vdefString3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string vdefString2 {
            get {
                return this.vdefString2Field;
            }
            set {
                this.vdefString2Field = value;
                this.RaisePropertyChanged("vdefString2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string customerSysPort {
            get {
                return this.customerSysPortField;
            }
            set {
                this.customerSysPortField = value;
                this.RaisePropertyChanged("customerSysPort");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<decimal> vdefDouble2 {
            get {
                return this.vdefDouble2Field;
            }
            set {
                this.vdefDouble2Field = value;
                this.RaisePropertyChanged("vdefDouble2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble2Specified {
            get {
                return this.vdefDouble2FieldSpecified;
            }
            set {
                this.vdefDouble2FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble2Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public System.Nullable<decimal> vdefDouble3 {
            get {
                return this.vdefDouble3Field;
            }
            set {
                this.vdefDouble3Field = value;
                this.RaisePropertyChanged("vdefDouble3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble3Specified {
            get {
                return this.vdefDouble3FieldSpecified;
            }
            set {
                this.vdefDouble3FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<decimal> vdefDouble1 {
            get {
                return this.vdefDouble1Field;
            }
            set {
                this.vdefDouble1Field = value;
                this.RaisePropertyChanged("vdefDouble1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefDouble1Specified {
            get {
                return this.vdefDouble1FieldSpecified;
            }
            set {
                this.vdefDouble1FieldSpecified = value;
                this.RaisePropertyChanged("vdefDouble1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string customerSysCode {
            get {
                return this.customerSysCodeField;
            }
            set {
                this.customerSysCodeField = value;
                this.RaisePropertyChanged("customerSysCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string customerSyspwd {
            get {
                return this.customerSyspwdField;
            }
            set {
                this.customerSyspwdField = value;
                this.RaisePropertyChanged("customerSyspwd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<int> vdefInteger3 {
            get {
                return this.vdefInteger3Field;
            }
            set {
                this.vdefInteger3Field = value;
                this.RaisePropertyChanged("vdefInteger3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefInteger3Specified {
            get {
                return this.vdefInteger3FieldSpecified;
            }
            set {
                this.vdefInteger3FieldSpecified = value;
                this.RaisePropertyChanged("vdefInteger3Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string customerSysIp {
            get {
                return this.customerSysIpField;
            }
            set {
                this.customerSysIpField = value;
                this.RaisePropertyChanged("customerSysIp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public System.Nullable<int> vdefInteger1 {
            get {
                return this.vdefInteger1Field;
            }
            set {
                this.vdefInteger1Field = value;
                this.RaisePropertyChanged("vdefInteger1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefInteger1Specified {
            get {
                return this.vdefInteger1FieldSpecified;
            }
            set {
                this.vdefInteger1FieldSpecified = value;
                this.RaisePropertyChanged("vdefInteger1Specified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public System.Nullable<int> vdefInteger2 {
            get {
                return this.vdefInteger2Field;
            }
            set {
                this.vdefInteger2Field = value;
                this.RaisePropertyChanged("vdefInteger2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vdefInteger2Specified {
            get {
                return this.vdefInteger2FieldSpecified;
            }
            set {
                this.vdefInteger2FieldSpecified = value;
                this.RaisePropertyChanged("vdefInteger2Specified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnApplyInfo", WrapperNamespace="http://ReturnApplyService/xsd", IsWrapped=true)]
    public partial class returnApplyInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ReturnApplyService/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public mms.ReturnApplyService.ReturnApplyParam returnapplyparaminfo;
        
        public returnApplyInfoRequest() {
        }
        
        public returnApplyInfoRequest(mms.ReturnApplyService.ReturnApplyParam returnapplyparaminfo) {
            this.returnapplyparaminfo = returnapplyparaminfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="returnApplyInfoResponse", WrapperNamespace="http://ReturnApplyService/xsd", IsWrapped=true)]
    public partial class returnApplyInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ReturnApplyService/xsd", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", IsNullable=true)]
        public mms.ReturnApplyService.ReturnApplyResponse[] @return;
        
        public returnApplyInfoResponse() {
        }
        
        public returnApplyInfoResponse(mms.ReturnApplyService.ReturnApplyResponse[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReturnApplyServicePortTypeChannel : mms.ReturnApplyService.ReturnApplyServicePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReturnApplyServicePortTypeClient : System.ServiceModel.ClientBase<mms.ReturnApplyService.ReturnApplyServicePortType>, mms.ReturnApplyService.ReturnApplyServicePortType {
        
        public ReturnApplyServicePortTypeClient() {
        }
        
        public ReturnApplyServicePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReturnApplyServicePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReturnApplyServicePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReturnApplyServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mms.ReturnApplyService.returnApplyInfoResponse mms.ReturnApplyService.ReturnApplyServicePortType.returnApplyInfo(mms.ReturnApplyService.returnApplyInfoRequest request) {
            return base.Channel.returnApplyInfo(request);
        }
        
        public mms.ReturnApplyService.ReturnApplyResponse[] returnApplyInfo(mms.ReturnApplyService.ReturnApplyParam returnapplyparaminfo) {
            mms.ReturnApplyService.returnApplyInfoRequest inValue = new mms.ReturnApplyService.returnApplyInfoRequest();
            inValue.returnapplyparaminfo = returnapplyparaminfo;
            mms.ReturnApplyService.returnApplyInfoResponse retVal = ((mms.ReturnApplyService.ReturnApplyServicePortType)(this)).returnApplyInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mms.ReturnApplyService.returnApplyInfoResponse> mms.ReturnApplyService.ReturnApplyServicePortType.returnApplyInfoAsync(mms.ReturnApplyService.returnApplyInfoRequest request) {
            return base.Channel.returnApplyInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<mms.ReturnApplyService.returnApplyInfoResponse> returnApplyInfoAsync(mms.ReturnApplyService.ReturnApplyParam returnapplyparaminfo) {
            mms.ReturnApplyService.returnApplyInfoRequest inValue = new mms.ReturnApplyService.returnApplyInfoRequest();
            inValue.returnapplyparaminfo = returnapplyparaminfo;
            return ((mms.ReturnApplyService.ReturnApplyServicePortType)(this)).returnApplyInfoAsync(inValue);
        }
    }
}
